***(
Copyright 2023-2026 Universitat Politècnica de València, Spain

This program is free software: you can redistribute it and/or modify it under the terms 
of the GNU General Public License as published by the Free Software Foundation, either 
version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
)***

set show advisories off .

fmod DM-CHECK-META is
    pr META-MODULE .
    pr META-LEVEL .
    pr META-TERM .
    pr CONVERSION .
    pr STRING-OPS .

    var F : Qid .   
    var V : Variable .  
    var NTL : NeTermList .   
    vars T T' : Term .   
    var N : Nat .   
    var TL : TermList .   
    vars SB SB' : Substitution .   
    var VarType : Type .   
    var CO : Context .
    var COL : NeCTermList .
    var NCTL : NeCTermList .   
    var C : Constant .   
    vars TS TS' SKO : TermSet .  
    var NTS : NeTermSet .
    var GT : GroundTerm .
    var S : Sort .
    var COND : Condition .

    --- Define term sets
    sorts NeTermSet TermSet .
    subsort Term < NeTermSet < TermSet .

    op mt : -> TermSet [ ctor ] .
    op _;;_ : TermSet TermSet -> TermSet [ assoc comm id: mt ] .
    op _;;_ : NeTermSet TermSet -> NeTermSet [ assoc comm id: mt ] .
    eq T:Term ;; T:Term = T:Term .

    --- Get the variables of conditions, termlists and termsets
    op getVars : Condition -> TermSet .
    op getVars : TermList -> TermSet .
    op getVars : TermSet -> TermSet .
    eq getVars((nil).Condition) = mt .
    eq getVars(empty) = mt .
    eq getVars(mt) = mt .
    eq getVars(C) = mt .
    eq getVars(V) = V .
    eq getVars(F[NTL]) = getVars(NTL) .
    eq getVars((T, NTL)) = getVars(T) ;; getVars(NTL) .
    eq getVars((T ;; NTS)) = getVars(T) ;; getVars(NTS) .
    eq getVars((T : S) /\ COND) = getVars(T) ;; getVars(COND) .
    eq getVars((T = T') /\ COND) = getVars(T) ;; getVars(T') ;; getVars(COND) .
    eq getVars((T => T') /\ COND) = getVars(T) ;; getVars(T') ;; getVars(COND) .
    eq getVars((T' := T) /\ COND) = getVars(T) ;; getVars(T') ;; getVars(COND) .

    --- Get the variables of a substitution range
    op getRangeVars : Substitution -> TermSet .
    eq getRangeVars((none).Substitution) = mt .
    eq getRangeVars(V <- T ; SB) = getVars(T) ;; getRangeVars(SB) .

    --- Get the solo constants of a substitution range
    op getRangeConst : Substitution -> TermSet .
    eq getRangeConst((none).Substitution) = mt .
    eq getRangeConst(V <- C ; SB) = C ;; getRangeConst(SB) .
    eq getRangeConst(V <- T ; SB) = getRangeConst(SB) [owise] .

    --- Get the variables of a substitution domain
    op getDomainVars : Substitution -> TermSet .
    eq getDomainVars((none).Substitution) = mt .
    eq getDomainVars(V <- T ; SB) = V ;; getDomainVars(SB) .

    --- Apply substitutions
    op applySub : TermSet Substitution -> TermSet .
    op applySub : TermList Substitution -> TermList .
    op applySub : Term Substitution -> Term .
    eq applySub((mt).TermSet, SB) = mt .
    eq applySub(empty, SB) = empty .
    eq applySub(V, (V <- T ; SB)) = T .
    eq applySub(F[NTL], SB) = F[applySub(NTL, SB)] .
    eq applySub((T, NTL), SB) = applySub(T, SB), applySub(NTL, SB) .
    eq applySub((T ;; NTS), SB) = applySub(T,SB) ;; applySub(NTS,SB) .
    eq applySub(T, SB) = T [ owise ] .

    op applySub : Condition Substitution -> TermList .
    eq applySub((nil).Condition, SB) = empty .
    eq applySub((T = T' /\ COND), SB) = applySub('_=_[T,T'], SB) , applySub(COND, SB) .
    eq applySub((T : S) /\ COND, SB) = applySub(COND, SB) .
    eq applySub((T => T') /\ COND, SB) = applySub(COND, SB) .
    eq applySub((T' := T) /\ COND, SB) = applySub(COND, SB) .

    op applySub : Substitution Substitution -> Substitution .
    eq applySub((none).Substitution, SB) = none .
    eq applySub(V <- T ; SB, SB') = V <- applySub(T, SB') ; applySub(SB, SB') .

    op applySubRangeDomain : Substitution Substitution -> Substitution .
    eq applySubRangeDomain((none).Substitution, SB) = none .
    eq applySubRangeDomain(V <- T ; SB, SB') = applySub(V, SB') <- applySub(T, SB') ; applySub(SB, SB') .
    
    --- Get all the variables of a substitution 
    op getAllVars : Substitution -> TermSet .
    eq getAllVars((none).Substitution) = mt .
    eq getAllVars(V <- T ; SB) = V ;; getVars(T) ;; getAllVars(SB) .

    --- Remove repetitions from a variable set
    op disjunctVars : TermSet -> TermSet .
    eq disjunctVars(mt) = mt .
    eq disjunctVars(T) = T .
    eq disjunctVars(NTS ;; NTS ;; TS) = disjunctVars(NTS ;; TS) .
    eq disjunctVars(NTS) = NTS [owise] .

    --- Count the variables in a list or set
    op countVars : TermList -> Nat .
    op countVars : TermSet -> Nat .
    eq countVars(empty) = 0 .
    eq countVars(mt) = 0 .
    eq countVars(GT) = 0 .
    eq countVars(V) = 1 .
    eq countVars(F[NTL]) = countVars(NTL) .
    eq countVars(T ;; NTS) = countVars(T) + countVars(NTS) .
    eq countVars((T, NTL)) = countVars(T) + countVars(NTL) .

    --- Rename a set of variables to "$" notation
    op rename : TermSet Nat -> Substitution .
    eq rename(mt, N) = none .
    eq rename(V ;; TS, N) = V <- qid("$" + string(N,10) + ":" + string(getType(V))) ; rename(TS, N + 1) .

    --- Convert vars to constants
    op varsToConst : TermSet -> Substitution .
    eq varsToConst(mt) = none .
    eq varsToConst(V ;; TS) = V <- qid(string(getName(V)) + "." + string(getType(V))) ; varsToConst(TS) .
    
    --- Convert constants to vars
    op constToVars : Term TermSet -> TermSet .
    eq constToVars(empty, TS) = empty .
    eq constToVars(C, (C ;; TS)) = qid(string(getName(C)) + ":" + string(getType(C))) .
    eq constToVars(C, TS) = C [owise] .    
    eq constToVars(V, TS) = V .
    eq constToVars(F[NTL], TS) = F[constToVars(NTL, TS)] .
    eq constToVars((T, NTL), TS) = (constToVars(T, TS), constToVars(NTL, TS)) .

    --- Replace a hole in a term
    op replaceHole : Context Term -> Term .
    eq replaceHole([],T) = T .
    eq replaceHole(F[COL],T) = F[replaceHole(COL,T)] .
    eq replaceHole((CO,TL),T) = (replaceHole(CO,T),TL) [ owise ] .
    eq replaceHole((T,COL),T') = (T,replaceHole(COL,T')) [ owise ] .

    op freeze : Substitution -> Substitution .
    op freeze : TermSet -> TermSet .
    op freeze : TermList -> TermList .
    op freeze : Term -> Term .
    eq freeze((none).Substitution) = none .
    eq freeze((mt).TermSet) = mt .
    eq freeze(empty) = empty .
    eq freeze(C) = C .
    eq freeze(V) = qid(string(getName(V)) + "." + string(getType(V))) .
    eq freeze(F[NTL]) = F[freeze(NTL)] .
    eq freeze((T,NTL)) = (freeze(T),freeze(NTL)) .
    eq freeze(T ;; NTS) = freeze(T) ;; freeze(NTS) .
    eq freeze(V <- T ; SB) = (V <- freeze(T)) ; freeze(SB) .

    op freeze : NeCTermList -> NeCTermList .
    op freeze : Context -> Context .
    eq freeze([]) = [] .
    eq freeze(F[NCTL]) = F[freeze(NCTL)] .
    eq freeze((T,NCTL)) = freeze(T), freeze(NCTL) .
    eq freeze((CO,NTL)) = freeze(CO), freeze(NTL) .

    op freeze : Substitution TermSet -> Substitution .
    op freeze : TermSet TermSet -> TermSet .
    op freeze : TermList TermSet -> TermList .
    op freeze : Term TermSet -> Term .
    eq freeze((none).Substitution, SKO) = none .
    eq freeze((mt).TermSet, SKO) = mt .
    eq freeze(empty, SKO) = empty .
    eq freeze(C, SKO) = C .
    eq freeze(V, SKO) = if (V in SKO) or-else (freeze(V) in SKO) then qid(string(getName(V)) + "." + string(getType(V))) else V fi .
    eq freeze(F[NTL], SKO) = F[freeze(NTL, SKO)] .
    eq freeze((T,NTL), SKO) = (freeze(T, SKO),freeze(NTL, SKO)) .
    eq freeze(T ;; NTS, SKO) = freeze(T, SKO) ;; freeze(NTS, SKO) .
    eq freeze(V <- T ; SB, SKO) = (V <- freeze(T, SKO)) ; freeze(SB, SKO) .

    op freeze : NeCTermList TermSet -> NeCTermList .
    op freeze : Context TermSet -> Context .
    eq freeze(CO, mt) = CO .
    eq freeze([], SKO) = [] .
    eq freeze(F[NCTL], SKO) = F[freeze(NCTL, SKO)] .
    eq freeze((T,NCTL), SKO) = freeze(T, SKO), freeze(NCTL, SKO) .
    eq freeze((CO,NTL), SKO) = freeze(CO, SKO), freeze(NTL, SKO) .

    op unfreeze : Substitution -> Substitution .
    op unfreeze : TermSet -> TermSet .
    op unfreeze : TermList -> TermList .
    op unfreeze : Term -> Term .
    eq unfreeze((none).Substitution) = none .
    eq unfreeze((mt).TermSet) = mt .
    eq unfreeze(empty) = empty .
    eq unfreeze(C) = if startsWith(string(C), "$") then qid(string(getName(C)) + ":" + string(getType(C))) else C fi .
    eq unfreeze(V) = V .
    eq unfreeze(F[NTL]) = F[unfreeze(NTL)] .
    eq unfreeze((T,NTL)) = (unfreeze(T),unfreeze(NTL)) .
    eq unfreeze(T ;; NTS) = unfreeze(T) ;; unfreeze(NTS) .
    eq unfreeze(V <- T ; SB) = (V <- unfreeze(T)) ; unfreeze(SB) .

    op unfreeze : NeCTermList -> NeCTermList .
    op unfreeze : Context -> Context .
    eq unfreeze([]) = [] .
    eq unfreeze(F[NCTL]) = F[unfreeze(NCTL)] .
    eq unfreeze((T,NCTL)) = unfreeze(T), unfreeze(NCTL) .
    eq unfreeze((CO,NTL)) = unfreeze(CO), unfreeze(NTL) .

    op unfreeze : Substitution TermSet -> Substitution .
    op unfreeze : TermSet TermSet -> TermSet .
    op unfreeze : TermList TermSet -> TermList .
    op unfreeze : Term TermSet -> Term .
    eq unfreeze((none).Substitution, SKO) = none .
    eq unfreeze(TS, mt) = TS .
    eq unfreeze(TL, mt) = TL .
    eq unfreeze((mt).TermSet, SKO) = mt .
    eq unfreeze(empty, SKO) = empty .
    eq unfreeze(C, SKO) = if (C in SKO) or-else (qid(string(getName(C)) + ":" + string(getType(C))) in SKO) then qid(string(getName(C)) + ":" + string(getType(C))) else C fi .
    eq unfreeze(V, SKO) = V .
    eq unfreeze(F[NTL], SKO) = F[unfreeze(NTL, SKO)] .
    eq unfreeze((T ;; NTS), SKO) = unfreeze(T, SKO) ;; unfreeze(NTS, SKO) .
    eq unfreeze((T,NTL), SKO) = unfreeze(T, SKO), unfreeze(NTL, SKO) .
    eq unfreeze(T, SKO) = T [ owise ] .
    eq unfreeze(V <- T ; SB, SKO) = (V <- unfreeze(T, SKO)) ; unfreeze(SB, SKO) .

    op unfreeze : NeCTermList TermSet -> NeCTermList .
    op unfreeze : Context TermSet -> Context .
    eq unfreeze(CO, mt) = CO .
    eq unfreeze([], SKO) = [] .
    eq unfreeze(F[NCTL], SKO) = F[unfreeze(NCTL, SKO)] .
    eq unfreeze((T,NCTL), SKO) = unfreeze(T, SKO), unfreeze(NCTL, SKO) .
    eq unfreeze((CO,NTL), SKO) = unfreeze(CO, SKO), unfreeze(NTL, SKO) .
endfm

fmod DM-CHECK-MODS is
    pr DM-CHECK-META .
    
    vars MOD F TP V LBL : Qid .   
    var IL : ImportList .   
    var SS : SortSet .   
    vars RLS RLS' RLS'' : RuleSet .   
    var SUBSS : SubsortDeclSet .   
    var OPS OPS' : OpDeclSet .   
    var MBS : MembAxSet .   
    vars EQS EQS' EQS'' : EquationSet .   
    var STTS : StratDeclSet .   
    var STTD : StratDefSet .   
    vars LHS LHS' RHS RHS' : Term . 
    vars T T' CTR CTR' CTR'' : Term .   
    vars ATS ATS' : AttrSet . 
    vars S S' : Sort .   
    vars COND COND1 COND2 COND3 : Condition .   
    var M : Module .   
    var C : Constant .   
    var TS : TermSet .   
    var NTS : NeTermSet .   
    vars NTL NTL' : NeTermList .
    var N : Nat .
    
    --- Add the necessary operators and modify rules for conditional narrowing.
    op transformMod : Module -> Module .
    eq transformMod(mod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endm)
                = mod MOD is IL sorts SS ; 'DMCBool . SUBSS (OPS addOpDecls(SS)) MBS EQS transformRules(RLS) endm .
    eq transformMod(th MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endth)
                = th MOD is IL sorts SS ; 'DMCBool . SUBSS (OPS addOpDecls(SS)) MBS EQS transformRules(RLS) endth . 
    eq transformMod(smod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsm)
                = smod MOD is IL sorts SS ; 'DMCBool . SUBSS (OPS addOpDecls(SS)) MBS EQS transformRules(RLS) STTS STTD endsm .
    eq transformMod(sth MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsth)
                = sth MOD is IL sorts SS ; 'DMCBool . SUBSS (OPS addOpDecls(SS)) MBS EQS transformRules(RLS) STTS STTD endsth .

    --- Add the dmc/\, dmc> and = operators to handle conditions.
    op addOpDecls : SortSet -> OpDeclSet .
    eq addOpDecls(none) = none .
    eq addOpDecls(SS)
      = (op '_dmc/\_ : 'DMCBool 'DMCBool -> 'DMCBool [ assoc ctor ] .) addOpDeclsAux(SS) .
    op addOpDeclsAux : SortSet -> OpDeclSet .
    eq addOpDeclsAux(none) = none .
    eq addOpDeclsAux(S ; SS)
      = (op '_dmc>_ : 'DMCBool S -> S [ ctor ] .)
        (op '_dmc=_ : S S -> 'DMCBool [ ctor ] .)
        addOpDeclsAux(SS) .

    --- Transform conditional rules and extract the constraints
    op transformRules : RuleSet -> RuleSet .
    eq transformRules(RLS) = transformNuITPConditions(RLS) .

    op transformNuITPConditions : RuleSet -> RuleSet .
    eq transformNuITPConditions(RLS' (crl LHS => RHS if nil [ATS] .) RLS'')
                = transformNuITPConditions(RLS' RLS'') (rl LHS => RHS [ATS narrowing] .) .
    eq transformNuITPConditions(RLS' (crl LHS => RHS if (CTR = CTR') /\ COND1 [ATS] .) RLS'')
                = transformNuITPConditions(RLS' transformNuITPConditionsAux(crl LHS => '_dmc>_['_dmc=_[CTR,CTR'],RHS] if COND1 [ATS] .) RLS'') .
    eq transformNuITPConditions(RLS') = RLS' [owise] .

    op transformNuITPConditionsAux : Rule -> Rule .
    eq transformNuITPConditionsAux(crl LHS => RHS if nil [ATS] .)
                =  (rl (LHS) => RHS [ATS narrowing] .) .
    eq transformNuITPConditionsAux(crl LHS => '_dmc>_[CTR,RHS] if (CTR' = CTR'') /\ COND1 [ATS] .)
                = transformNuITPConditionsAux(crl LHS => '_dmc>_['_dmc/\_[CTR,'_dmc=_[CTR',CTR'']],RHS] if COND1 [ATS] .) .
    eq transformNuITPConditionsAux(crl LHS => RHS if COND1 [ATS] .)
                = (crl LHS => RHS if COND1 [ATS] .) [owise] .

    op addAllVariants : Module -> Module .
    eq addAllVariants(mod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endm)
                = mod MOD is IL sorts SS . SUBSS OPS MBS allEqVariant(EQS) RLS endm .
    eq addAllVariants(th MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endth)
                = th MOD is IL sorts SS . SUBSS OPS MBS allEqVariant(EQS) RLS endth . 
    eq addAllVariants(smod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsm)
                = smod MOD is IL sorts SS . SUBSS OPS MBS allEqVariant(EQS) RLS STTS STTD endsm .
    eq addAllVariants(sth MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsth)
                = sth MOD is IL sorts SS . SUBSS OPS MBS allEqVariant(EQS) RLS STTS STTD endsth .

    op allEqVariant : EquationSet -> EquationSet .
    eq allEqVariant(none) = none .
    eq allEqVariant((eq LHS = RHS [ATS] .) EQS) = (eq LHS = RHS [ATS variant] .) allEqVariant(EQS) .
    eq allEqVariant((ceq LHS = RHS if COND1 [ATS] .) EQS) = (ceq LHS = RHS if COND1 [ATS] .) allEqVariant(EQS) .

    op toOps : TermList -> OpDeclSet .
    op toOps : TermSet -> OpDeclSet .
    eq toOps(empty) = none .
    eq toOps(mt) = none .
    eq toOps(C) = (op getName(C) : nil -> getType(C) [ metadata("skolem") ] .) .
    eq toOps((C, NTL)) = (op getName(C) : nil -> getType(C) [ metadata("skolem") ] .) toOps(NTL) .
    eq toOps((C ;; NTS)) = (op getName(C) : nil -> getType(C) [ metadata("skolem") ] .) toOps(NTS) .

    op addOps : Module TermSet -> Module .
    eq addOps(M, TS) = addOps(M, toOps(TS)) .

    op addOps : Module OpDeclSet -> Module .
    eq addOps(mod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endm, OPS') 
        = mod MOD is IL sorts SS . SUBSS OPS OPS' MBS EQS RLS endm .
    eq addOps(th MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endth, OPS') 
        = th MOD is IL sorts SS . SUBSS OPS OPS' MBS EQS RLS endth .
    eq addOps(smod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsm, OPS') 
        = smod MOD is IL sorts SS . SUBSS OPS OPS' MBS EQS RLS STTS STTD endsm .
    eq addOps(sth MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsth, OPS') 
        = sth MOD is IL sorts SS . SUBSS OPS OPS' MBS EQS RLS STTS STTD endsth .
    eq addOps(M, OPS) = M [ owise ] .

    op extModule : Qid -> Module .
    eq extModule(MOD) = extModule(upModule(MOD, true)) .

    op extModule : Module -> Module .
    eq extModule(mod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endm) 
        = mod MOD is IL (protecting 'NuITP-CLAUSE .) sorts SS . SUBSS OPS MBS EQS RLS endm .
    eq extModule(th MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endth) 
        = th MOD is IL (protecting 'NuITP-CLAUSE .) sorts SS . SUBSS OPS MBS EQS RLS endth .
    eq extModule(smod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsm) 
        = smod MOD is IL (protecting 'NuITP-CLAUSE .) sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsm .
    eq extModule(sth MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsth) 
        = sth MOD is IL (protecting 'NuITP-CLAUSE .) sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsth .

    op toRls : EquationSet -> RuleSet .
    eq toRls((none).EquationSet) = none .
    eq toRls((eq LHS = RHS [ variant ATS ] .) EQS) = (rl LHS => RHS [ narrowing ATS ] .) toRls(EQS) .
    eq toRls((eq LHS = RHS [ owise ATS ] .) EQS) = (rl LHS => RHS [ ATS ] .) toRls(EQS) .
    eq toRls((eq LHS = RHS [ ATS ] .) EQS) = (rl LHS => RHS [ narrowing ATS ] .) toRls(EQS) [ owise ] .
    eq toRls((ceq LHS = RHS if COND [ ATS ] .) EQS) = (crl LHS => RHS if COND [ ATS ] .) toRls(EQS) .

    op toRls : EquationSet Term Nat -> RuleSet .
    eq toRls((none).EquationSet, T, N) = none .
    eq toRls((eq LHS = RHS [ owise ATS ] .) EQS, T, N) = (rl LHS => RHS [ label(qid("DM-CHECK-RL#" + string(N,10)))] .) toRls(EQS, T, N + 1) .
    eq toRls((eq F[NTL] = RHS [ variant ATS ] .) EQS, F[NTL'], N) = (rl F[NTL] => RHS [ narrowing label(qid("DM-CHECK-RL#" + string(N,10))) ] .) toRls(EQS, F[NTL'], N + 1) .
    eq toRls((eq F[NTL] = RHS [ ATS ] .) EQS, F[NTL'], N) = (rl F[NTL] => RHS [ narrowing label(qid("DM-CHECK-RL#" + string(N,10))) ] .) toRls(EQS, F[NTL'], N + 1) [ owise ] .
    eq toRls((ceq F[NTL] = RHS if COND [ ATS ] .) EQS, F[NTL'], N) = (crl F[NTL] => RHS if COND [ ATS label(qid("DM-CHECK-RL#" + string(N,10)))] .) toRls(EQS, F[NTL'], N + 1) .
    eq toRls(EQS, T, N) = none [ owise ] .

    op setRls : Module RuleSet -> Module .
    eq setRls(mod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endm, RLS') 
        = mod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS' endm .
    eq setRls(th MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endth, RLS') 
        = th MOD is IL sorts SS . SUBSS OPS MBS EQS RLS' endth .
    eq setRls(smod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsm, RLS') 
        = smod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS' STTS STTD endsm .
    eq setRls(sth MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsth, RLS') 
        = sth MOD is IL sorts SS . SUBSS OPS MBS EQS RLS' STTS STTD endsth . 
    eq setRls(M, RLS) = M [ owise ] .

    op setEqs : Module EquationSet -> Module .
    eq setEqs(mod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endm, EQS') 
        = mod MOD is IL sorts SS . SUBSS OPS MBS EQS' RLS endm .
    eq setEqs(th MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endth, EQS') 
        = th MOD is IL sorts SS . SUBSS OPS MBS EQS' RLS endth .
    eq setEqs(smod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsm, EQS') 
        = smod MOD is IL sorts SS . SUBSS OPS MBS EQS' RLS STTS STTD endsm .
    eq setEqs(sth MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsth, EQS') 
        = sth MOD is IL sorts SS . SUBSS OPS MBS EQS' RLS STTS STTD endsth . 
    eq setEqs(M, EQS) = M [ owise ] .

    op euR : Module Term -> Module [ memo ] .
    eq euR(M, F[NTL]) = setRls(setEqs(M, (none).EquationSet), toRls(getEqs(M), F[NTL], 0)) .

    op countNarrowRls : Module -> Nat .
    eq countNarrowRls(mod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endm) = countNarrowRls'(RLS) .
    eq countNarrowRls(th MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endth) = countNarrowRls'(RLS) .
    eq countNarrowRls(smod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsm) = countNarrowRls'(RLS) .
    eq countNarrowRls(sth MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsth) = countNarrowRls'(RLS) .

    op countNarrowRls' : RuleSet -> Nat .
    eq countNarrowRls'(none) = 0 .
    eq countNarrowRls'((crl LHS => RHS if COND [ATS] .) RLS) = countNarrowRls'(RLS) .
    eq countNarrowRls'((rl LHS => RHS [ narrowing ATS ] .) RLS) = countNarrowRls'(RLS) .
    eq countNarrowRls'((rl LHS => RHS [ ATS ] .) RLS) = 1 + countNarrowRls'(RLS) [owise] .
endfm 

load NuITP.maude

mod DM-CHECK-SYNTAX is
    pr DM-CHECK-META .
    pr CONFIGURATION .
    pr NuITP-CLAUSE .

    --- Proof states
    sort ProofState .
    ops sat unsat open : -> ProofState [ ctor ] .

    --- Matcher List
    sorts Matcher NeMatcherList MatcherList .
    subsort Matcher < NeMatcherList < MatcherList .
    op _,_,_,_ : Nat Substitution? Term ProofState -> Matcher .
    
    op noMatch : -> MatcherList .
    op _;_ : MatcherList MatcherList -> MatcherList [ ctor assoc id: noMatch ]  .
    op _;_ : NeMatcherList MatcherList -> NeMatcherList [ ditto ] .
    op _;_ : MatcherList NeMatcherList -> NeMatcherList [ ditto ] .

    --- Node types (initial/generated/subsumed)
    sort NodeType .
    ops iNode gNode sNode itNode : -> NodeType .
    
    op term:_ : Term -> Attribute [ ctor ] . --- Term related to the state
    op lterm:_ : Term -> Attribute [ ctor ] . --- Left term related to the state (Intersection node)
    op rterm:_ : Term -> Attribute [ ctor ] . --- Right term related to the state (Intersection node)
    op pid:_ : Nat -> Attribute [ ctor ] . --- Parent ID
    op ctr:_ : Term -> Attribute [ ctor ] . --- Constraint related to the state
    op type:_ : Type -> Attribute [ ctor ] . --- Narrowing step type
    op ctx:_ : Context -> Attribute [ ctor ] . --- Narrowing step context
    op rule:_ : Qid -> AttributeSet [ ctor ] . --- Applied rule
    op sub:_ : Substitution -> Attribute [ ctor ] . --- Narrowing step term substitution
    op lsub:_ : Substitution -> Attribute [ ctor ] . --- Left substitution related to the state (Intersection node)
    op rsub:_ : Substitution -> Attribute [ ctor ] . --- Right substitution related to the state (Intersection node)
    op rlsub:_ : Substitution -> Attribute [ ctor ] . --- Narrowing step rule substitution
    op acsub:_ : Substitution -> Attribute [ ctor ] . --- Accumulated substitution
    op match:_ : MatcherList -> Attribute [ ctor ] . --- Matcher list (folding)
    op ntype:_ : NodeType -> Attribute [ ctor ] . --- Node type
    op ndepth:_ : Nat -> Attribute [ ctor ] . --- Node depth
    op fold:_ : Bool -> Attribute [ ctor ] . --- Folded? (Meaning that a matcher was sat)

    sorts Node NeNodeList NodeList . 
    subsort Node < NeNodeList < NodeList .
    op {_:_} : Nat AttributeSet -> Node [ ctor ] .
    
    op nil : -> NodeList [ ctor ] .
    op _;_ : NodeList NodeList -> NodeList [ assoc id: nil ] . 
    op _;_ : NeNodeList NodeList -> NeNodeList [ ditto ] . 
    op _;_ : NodeList NeNodeList -> NeNodeList [ ditto ] .

    op mod:_ : Module -> Attribute [ ctor ] .
    op prev:_ : NodeList -> Attribute [ ctor ] . --- Previous nodes
    op curr:_ : NodeList -> Attribute [ ctor ] . --- Current nodes
    op next:_ : NodeList -> Attribute [ ctor ] . --- Future nodes
    op init:_ : NodeList -> Attribute [ ctor ] . --- Initial nodes
    op init':_ : NodeList -> Attribute [ ctor ] . --- Initial nodes
    op inter:_ : NodeList -> Attribute [ ctor ] . --- Intersection nodes
    op depth:_ : Nat -> Attribute [ ctor ] . --- Max depth
    op cdepth:_ : Nat -> Attribute [ ctor ] . --- Current depth
    op vos:_ : VariantOptionSet -> Attribute [ ctor ] .
    op lemmas:_ : TermSet -> Attribute [ ctor ] .
    op idcount:_ : Nat -> Attribute [ ctor ] . --- ID counter
    op vcount:_ : Nat -> Attribute [ ctor ] . --- Variable counter

    --- State
    sort DMCState .
    op <_> : AttributeSet -> DMCState .
endm

mod DM-CHECK-OUTPUT is
    pr DM-CHECK-SYNTAX .
    
    sort ParentNode ParentNodeList .
    subsort ParentNode < ParentNodeList .
    
    op noParents : -> ParentNodeList .
    op _,_ : ParentNodeList ParentNodeList -> ParentNodeList [ ctor assoc id: noParents ] .
    op [_,_,_,_,_] : Nat Term Term Substitution Nat -> ParentNode [ ctor ] .

    sort ChildNode ChildNodeList .
    subsort ChildNode < ChildNodeList .

    op noChildren : -> ChildNodeList .
    op _,_ : ChildNodeList ChildNodeList -> ChildNodeList [ ctor assoc id: noChildren ] .
    op [_,_,_,_,_,_,_,_,_] : Nat Nat Term Term Qid Substitution Substitution MatcherList Nat -> ChildNode [ ctor ] . --- Check Invariant
    op [_,_,_,_,_,_] : Nat Term Term Substitution MatcherList Nat -> ChildNode [ ctor ] . --- Check Subsumption
    op [_,_,_,_,_,_,_] : Nat Term Term Term Term Substitution Substitution -> ChildNode [ ctor ] . --- Check Intersection

    sort DMCOutput .
    op noSolution : -> DMCOutput [ ctor ] .
    op _||_ : ParentNodeList ChildNodeList -> DMCOutput [ ctor ] .
endm

mod DM-CHECK-CORE is
    pr DM-CHECK-OUTPUT .
    pr DM-CHECK-MODS .
    pr NuITP-EXT .

    var M : Module .
    vars NODES NODES' NODES'' NODES''' : NodeList .
    vars NENODES NENODES' : NeNodeList .
    vars NODE NODE' : Node .
    vars ID ID' PID N IDCOUNT VCOUNT MCOUNT UCOUNT DEPTH : Nat .
    vars NL NL' NL'' : NatList .
    var QL : QidList .
    vars T T' T'' CTR CTR' GS : Term .
    var LEMMAS TS : TermSet .
    var TL TL' TL'' TL''' : TermList .
    vars NTL NTL' : NeTermList .
    var VOS : VariantOptionSet .
    vars ACSB SB SB' : Substitution .
    vars NATTRS NATTRS' : AttributeSet .
    var TP : Type .
    var CTX : Context .
    vars Q Q' F MOD : Qid .
    var NEML : NeMatcherList .
    vars MLIST MLIST' : MatcherList .
    var UTRIPLE : UnificationTriple .
    var PARENTS : ParentNodeList .
    vars CHILDREN CHILDREN' : ChildNodeList .
    var CHILD : ChildNode .
    var NTS : NeTermSet .
    var RL : Qid .
    var V : Variable .
    var C : Constant .
    var IL : ImportList .   
    var SS : SortSet .   
    var SUBSS : SubsortDeclSet .   
    var OPS : OpDeclSet .   
    var MBS : MembAxSet .   
    var EQS : EquationSet .   
    vars RLS : RuleSet .   
    var STTS : StratDeclSet .   
    var STTD : StratDefSet .

    op callNuITP : Module Term TermSet -> ProofState .
    eq callNuITP(M, '_->_[CTR,'true.NuITP-Bool], LEMMAS) = sat .
    eq callNuITP(M, '_->_[CTR,'_/\_['true.NuITP-Bool, CTR']], LEMMAS) 
        = callNuITP(M, '_->_[CTR, CTR'], LEMMAS) .
    eq callNuITP(M, '_->_[CTR,'_/\_[CTR', 'true.NuITP-Bool]], LEMMAS) 
        = callNuITP(M, '_->_[CTR, CTR'], LEMMAS) .
    eq callNuITP(M, CTR, LEMMAS) 
        = metaNuITPCheck(M, CTR, LEMMAS) .

    --- Check an invariant using the NuITP
    ---op callNuITP : Module Term TermSet -> ProofState .
    ---ceq callNuITP(M, CTR, mt) = 
    ---    if (GS == 'true.Bool)
    ---    then sat
    ---    else if (GS == 'false.Bool) then unsat else open fi
    ---    fi
    ---if GS := getTerm(metaRewrite(upModule('NuITP-EXT, false), 'metaNuITPCheck[upTerm(M),upTerm(CTR)], unbounded)) .

    --- Count the nodes in a list
    op countNodes : NodeList -> Nat .
    eq countNodes(nil) = 0 .
    eq countNodes(NODE ; NODES) = s(countNodes(NODES)) .
    
    --- Count the children in a list
    op countChildren : ChildNodeList -> Nat .
    eq countChildren(noChildren) = 0 .
    eq countChildren(CHILD , CHILDREN) = s(countChildren(CHILDREN)) .

    --- Get the variables of children
    op getVars : ChildNodeList -> TermSet .
    eq getVars(noChildren) = mt .
    eq getVars([ ID, PID, T, CTR, RL, SB, ACSB, MLIST, DEPTH ], CHILDREN) 
        = getVars(T) ;; getVars(CTR) ;; getVars(CHILDREN) .
    eq getVars([ ID, T, CTR, ACSB, MLIST, DEPTH ], CHILDREN) 
        = getVars(T) ;; getVars(CTR) ;; getVars(CHILDREN) .

    --- Count the variables in a list of nodes
    op countNodeVars : NodeList -> Nat .
    eq countNodeVars(nil) = 0 .
    eq countNodeVars({ID : term: T, acsub: ACSB, ctr: CTR, NATTRS} ; NODES) 
        = countVars(disjunctVars(getVars((T, CTR)) ;; getRangeVars(ACSB))) + countNodeVars(NODES) .

    --- Check constraints for a list of nodes. Remove node if unsat
    op checkConstraints : Module NodeList TermSet -> NodeList .
    eq checkConstraints(M, nil, LEMMAS) = nil .
    eq checkConstraints(M, {ID : ctr: CTR, NATTRS} ; NODES, LEMMAS) 
        = if callNuITP(M, '_->_['true.NuITP-Bool, CTR], LEMMAS) == unsat
          then checkConstraints(M, NODES, LEMMAS)
          else {ID : ctr: CTR, NATTRS} ; checkConstraints(M, NODES, LEMMAS) 
          fi .

    --- Convert initial term pairs into nodes
    op initNodes : Module TermList Nat Nat -> NodeList .
    eq initNodes(M, empty, IDCOUNT, VCOUNT) = nil . 
    eq initNodes(M, ('_|_[T, CTR], TL), IDCOUNT, VCOUNT)
        = {IDCOUNT : term: applySub(T, rename(getVars((T, CTR)), VCOUNT)), 
           ctr: applySub(CTR, rename(getVars((T, CTR)), VCOUNT)), 
           acsub: rename(getVars((T, CTR)), VCOUNT), ndepth: 0, ntype: iNode} ; 
           initNodes(M, TL, s(IDCOUNT), VCOUNT + countVars(getVars((T, CTR)))) .
    
    --- Convert initial term pairs into nodes (left part of check subsumed by)
    op initNodes' : Module TermList Nat Nat -> NodeList .
    eq initNodes'(M, empty, IDCOUNT, VCOUNT) = nil . 
    eq initNodes'(M, ('_|_[T, CTR], TL), IDCOUNT, VCOUNT)
        = {IDCOUNT : term: applySub(T, rename(getVars((T, CTR)), VCOUNT)), 
           ctr: applySub(CTR, rename(getVars((T, CTR)), VCOUNT)), 
           acsub: rename(getVars((T, CTR)), VCOUNT), ndepth: 0, ntype: sNode, 
           match: noMatch, fold: false} ; 
           initNodes'(M, TL, s(IDCOUNT), VCOUNT + countVars(getVars((T, CTR)))) .

    --- Convert initial term pairs into nodes (left and right parts of intersect)
    op initNodes'' : Module TermList Nat -> NodeList .
    eq initNodes''(M, empty, IDCOUNT) = nil . 
    eq initNodes''(M, ('_|_[T, CTR], TL), IDCOUNT)
        = {IDCOUNT : term: T, ctr: CTR, acsub: none, ndepth: 0, ntype: iNode} ; 
           initNodes''(M, TL, s(IDCOUNT)) .

    --- Deploy the children of a list of nodes
    op deployChildren : Module VariantOptionSet NodeList Nat -> NodeList .
    eq deployChildren(M, VOS, nil, IDCOUNT) = nil .
    eq deployChildren(M, VOS, NODES, IDCOUNT) 
        = genIDs(deployChildren'(M, VOS, NODES), IDCOUNT) .

    op deployChildren' : Module VariantOptionSet NodeList -> NodeList .
    eq deployChildren'(M, VOS, nil) = nil .
    eq deployChildren'(M, VOS, ({ID : ndepth: 0, NATTRS} ; NODES)) 
        = deployChildren''(M, VOS, {ID : ndepth: 0, NATTRS}, 0) ; deployChildren'(M, VOS, NODES) .
    eq deployChildren'(M, VOS, ({ID : fold: true, NATTRS} ; NODES)) 
        = deployChildren'(M, VOS, NODES) .
    eq deployChildren'(M, VOS, ({ID : fold: false, NATTRS} ; NODES)) 
        = deployChildren''(M, VOS, {ID : fold: false, NATTRS}, 0) ; deployChildren'(M, VOS, NODES) [owise] .

    op deployChildren'' : Module VariantOptionSet Node Nat -> NodeList .
    eq deployChildren''(M, VOS, {ID : term: T, ctr: CTR, acsub: ACSB, ndepth: DEPTH, NATTRS}, N)
        = if metaNarrowingApply(M, T, empty, '@, VOS, N) :: NarrowingApplyResult
          then 
            buildNode(metaNarrowingApply(M, T, empty, '@, VOS, N), ID, CTR, ACSB, s(DEPTH)) ;
            deployChildren''(M, VOS, {ID : term: T, ctr: CTR, acsub: ACSB, ndepth: DEPTH, NATTRS}, s(N))
          else
            nil
          fi .

    --- Generate new IDs for nodes starting from a number 
    op genIDs : NodeList Nat -> NodeList .
    eq genIDs(nil, N) = nil .
    eq genIDs(({ID : NATTRS} ; NODES), N) = {N : NATTRS} ; genIDs(NODES, s(N)) .

    --- Build a new node coming from a narrowing step
    op buildNode : NarrowingApplyResult Nat Term Substitution Nat -> Node .
    eq buildNode({('_dmc>_[CTR, T]), TP, CTX, Q, SB, SB', Q'}, ID, CTR', ACSB, DEPTH)
        = {0 : pid: ID, term: T, ctr: ('_/\_[applySub(CTR', SB), buildCtr(CTR)]), type: TP, ctx: CTX, rule: Q,
           sub: SB, rlsub: SB', acsub: applySub(ACSB, SB), match: noMatch, ndepth: DEPTH, ntype: gNode, fold: false} .
    eq buildNode({T, TP, CTX, Q, SB, SB', Q'}, ID, CTR, ACSB, DEPTH)
        = {0 : pid: ID, term: T, ctr: applySub(CTR, SB), type: TP, ctx: CTX, rule: Q,
           sub: SB, rlsub: SB', acsub: applySub(ACSB, SB), match: noMatch, ndepth: DEPTH, ntype: gNode, fold: false} [owise] .
    
    --- Build a constraint coming from a conditional step
    op buildCtr : TermList -> TermList .
    eq buildCtr('_dmc/\_[TL, TL']) = '_/\_[buildCtr(TL), buildCtr(TL')] .
    eq buildCtr('_dmc=_[TL, TL']) = '_=_[TL, TL'] .
    eq buildCtr((TL, TL')) = (buildCtr(TL), buildCtr(TL')) .
    eq buildCtr(T) = T [owise] .

    op removeTrueCtr : TermList -> Term .
    eq removeTrueCtr('_/\_[TL, 'true.NuITP-Bool, TL']) = removeTrueCtr('_/\_[TL, TL']) .
    eq removeTrueCtr('_/\_[T, NTL]) = '_/\_[removeTrueCtr(T), removeTrueCtr(NTL)] [owise] .
    eq removeTrueCtr('_/\_[T]) = removeTrueCtr(T) .
    eq removeTrueCtr((T, NTL)) = (removeTrueCtr(T), removeTrueCtr(NTL)) .
    eq removeTrueCtr(T) = T [owise] .

    --- Build a new intersection node coming from unifying two nodes
    op buildIntersectionNode : Term Term Term Term UnificationTriple -> Node .
    eq buildIntersectionNode(T, T', CTR, CTR', UTRIPLE)
        = {0 : lterm: T, rterm: T', lsub: getLhsSubstitution(UTRIPLE), rsub: getRhsSubstitution(UTRIPLE), ntype: itNode,
           ctr: ('_/\_[applySub(CTR, getLhsSubstitution(UTRIPLE)), applySub(CTR', getRhsSubstitution(UTRIPLE))])} .

    --- Rename the variables in a list of nodes
    op renameNodes : NodeList Nat -> NodeList .
    eq renameNodes(nil, VCOUNT) = nil .
    eq renameNodes({ID : term: T, ctr: CTR, sub: SB, acsub: ACSB, NATTRS} ; NODES, VCOUNT)
        = {ID : 
           term: applySub(T, rename(getVars((T, CTR)) ;; getRangeVars(ACSB), VCOUNT)),
           ctr: applySub(CTR, rename(getVars((T, CTR)) ;; getRangeVars(ACSB), VCOUNT)),
           sub: applySubRangeDomain(SB, rename(getVars((T, CTR)) ;; getRangeVars(ACSB), VCOUNT)),
           acsub: applySub(ACSB, rename(getVars((T, CTR)) ;; getRangeVars(ACSB), VCOUNT)), 
           NATTRS} ; 
           renameNodes(NODES, VCOUNT + countVars(getVars((T, CTR)) ;; getRangeVars(ACSB))) .
    eq renameNodes({ID : term: T, ctr: CTR, acsub: ACSB, NATTRS} ; NODES, VCOUNT)
        = {ID : 
           term: applySub(T, rename(getVars((T, CTR)) ;; getRangeVars(ACSB), VCOUNT)),
           ctr: applySub(CTR, rename(getVars((T, CTR)) ;; getRangeVars(ACSB), VCOUNT)),
           acsub: applySub(ACSB, rename(getVars((T, CTR)) ;; getRangeVars(ACSB), VCOUNT)), 
           NATTRS} ; 
           renameNodes(NODES, VCOUNT + countVars(getVars((T, CTR)) ;; getRangeVars(ACSB))) .

    --- Check the if a group of states is subsumed by others
    op checkSubsumption : Module NodeList NodeList VariantOptionSet TermSet -> NodeList .
    eq checkSubsumption(M, nil, NODES, VOS, LEMMAS) = nil .
    eq checkSubsumption(M, NODES, nil, VOS, LEMMAS) = NODES .
    eq checkSubsumption(M, NENODES, (NODES ; {ID : match: NEML, NATTRS} ; NODES'), VOS, LEMMAS) 
        = checkSubsumption(M, NENODES, (NODES ; NODES'), VOS, LEMMAS) .
    eq checkSubsumption(M, NENODES, NENODES', VOS, LEMMAS) 
        = checkSubsumption'(M, checkChildrenSubsumption(M, NENODES, NENODES, VOS, LEMMAS), NENODES', VOS, LEMMAS) [owise] .

    op checkSubsumption' : Module NodeList NodeList VariantOptionSet TermSet -> NodeList .
    eq checkSubsumption'(M, nil, NENODES, VOS, LEMMAS) = nil .
    eq checkSubsumption'(M, (NODE ; NODES), NENODES, VOS, LEMMAS) 
        = checkNodeSubsumption(M, NODE, NENODES, VOS, LEMMAS, 0) ; checkSubsumption'(M, NODES, NENODES, VOS, LEMMAS) .

    op checkChildrenSubsumption : Module NodeList NodeList VariantOptionSet TermSet -> NodeList .
    eq checkChildrenSubsumption(M, nil, NENODES, VOS, LEMMAS) = nil .
    eq checkChildrenSubsumption(M, (NODE ; NODES), (NODES' ; NODE ; NODES''), VOS, LEMMAS) 
        = if isFolded(checkNodeSubsumption(M, NODE, (NODES' ; NODES''), VOS, LEMMAS, 0))
          then 
            checkNodeSubsumption(M, NODE, (NODES' ; NODES''), VOS, LEMMAS, 0) ; checkChildrenSubsumption(M, NODES, (NODES' ; NODES''), VOS, LEMMAS) 
          else
            checkNodeSubsumption(M, NODE, (NODES' ; NODES''), VOS, LEMMAS, 0) ; checkChildrenSubsumption(M, NODES, (NODES' ; NODE ; NODES''), VOS, LEMMAS) 
          fi .
        
    --- Check the if a state is subsumed by others
    op checkNodeSubsumption : Module Node NodeList VariantOptionSet TermSet Nat -> Node .
    eq checkNodeSubsumption(M, NODE, nil, VOS, LEMMAS, MCOUNT) = NODE .
    eq checkNodeSubsumption(M, {ID : term: T, ctr: CTR, match: MLIST, NATTRS}, ({ID' : term: T', ctr: CTR', NATTRS'} ; NODES), VOS, LEMMAS, MCOUNT)
        = if metaVariantMatch(M, T' <=? T, empty, '@, VOS, MCOUNT) :: Substitution
          then
            checkNodeSubsumption'(M, 
                                  {ID : term: T, ctr: CTR, 
                                  match: (MLIST ; 
                                         (ID',
                                          metaVariantMatch(M, T' <=? T, empty, '@, VOS, MCOUNT),
                                          getTerm(metaRewrite(extModule(setRls(M, none)), '_->_[CTR,applySub(CTR', metaVariantMatch(M, T' <=? T, empty, '@, VOS, MCOUNT))], unbounded)),
                                          ---'_->_[CTR,applySub(CTR', metaVariantMatch(M, T' <=? T, empty, '@, VOS, MCOUNT))],
                                          callNuITP(M, '_->_[CTR,applySub(CTR', metaVariantMatch(M, T' <=? T, empty, '@, VOS, MCOUNT))], LEMMAS)
                                         )),
                                  NATTRS}, 
                                  ({ID' : term: T', ctr: CTR', NATTRS'} ; NODES), VOS, LEMMAS, MCOUNT)
          else
            checkNodeSubsumption(M, {ID : term: T, ctr: CTR, match: MLIST, NATTRS}, NODES, VOS, LEMMAS, 0)
          fi .

    op checkNodeSubsumption' : Module Node NodeList VariantOptionSet TermSet Nat -> Node .
    eq checkNodeSubsumption'(M, {ID : match: (MLIST ; (ID', SB, CTR, sat)), fold: false, NATTRS}, NODES, VOS, LEMMAS, MCOUNT)
        = {ID : match: (MLIST ; (ID', SB, CTR, sat)), fold: true, NATTRS} .
    eq checkNodeSubsumption'(M, NODE, NODES, VOS, LEMMAS, MCOUNT)
        = checkNodeSubsumption(M, NODE, NODES, VOS, LEMMAS, s(MCOUNT)) [owise] .

    --- Remove the patterns subsumed by others
    op rmvSubsumedPatterns : Module TermList TermSet -> TermList .
    eq rmvSubsumedPatterns(M, empty, LEMMAS) = empty .
    eq rmvSubsumedPatterns(M, T, LEMMAS) = T .
    eq rmvSubsumedPatterns(M, NTL, LEMMAS)
        = rmvSubsumedPatterns'(M, NTL, NTL, LEMMAS) [owise] .

    op isFolded : Node -> Bool .
    eq isFolded({ID : fold: true, NATTRS}) = true .
    eq isFolded({ID : fold: false, NATTRS}) = false .

    op rmvSubsumedPatterns' : Module TermList TermList TermSet -> TermList .
    eq rmvSubsumedPatterns'(M, empty, NTL, LEMMAS) = empty .
    eq rmvSubsumedPatterns'(M, (T, TL), (TL', T, TL''), LEMMAS) 
        = if rmvPatternSubsumption(M, T, (TL', TL''), LEMMAS, 0) == empty
          then
            rmvSubsumedPatterns'(M, TL, (TL', TL''), LEMMAS)
          else
            (T, rmvSubsumedPatterns'(M, TL, (TL', T, TL''), LEMMAS))
          fi .

    op rmvPatternSubsumption : Module Term TermList TermSet Nat -> TermList .
    eq rmvPatternSubsumption(M, T, empty, LEMMAS, MCOUNT) = T .
    eq rmvPatternSubsumption(M, '_|_[T, CTR], ('_|_[T', CTR'], TL), LEMMAS, MCOUNT) 
        = if metaVariantMatch(M, T' <=? T, empty, '@, none, MCOUNT) :: Substitution
          then
            if callNuITP(M, '_->_[CTR,applySub(CTR', metaVariantMatch(M, T' <=? T, empty, '@, none, MCOUNT))], LEMMAS) == sat
            then
               empty
            else
               rmvPatternSubsumption(M, '_|_[T, CTR], ('_|_[T', CTR'], TL), LEMMAS, MCOUNT + 1) 
            fi
          else
            rmvPatternSubsumption(M, '_|_[T, CTR], TL, LEMMAS, 0)
          fi .

    --- Intersect two lists of nodes
    op intersectLists : Module NodeList NodeList VariantOptionSet Nat -> NodeList .
    eq intersectLists(M, nil, NODES', VOS, IDCOUNT) = nil .
    eq intersectLists(M, NODES, nil, VOS, IDCOUNT) = nil .
    eq intersectLists(M, NENODES, NENODES', VOS, IDCOUNT) 
        =  genIDs(intersectLists'(M, NENODES, NENODES', VOS), IDCOUNT) .

    op intersectLists' : Module NodeList NodeList VariantOptionSet -> NodeList .
    eq intersectLists'(M, nil, NODES, VOS) = nil .
    eq intersectLists'(M, (NODE ; NODES), NENODES, VOS)
        = intersectNodeLists(M, NODE, NENODES, VOS) ; intersectLists'(M, NODES, NENODES, VOS) .

    --- Intersect a node with a list of nodes
    op intersectNodeLists : Module Node NodeList VariantOptionSet -> NodeList .
    eq intersectNodeLists(M, NODE, nil, VOS) = nil .
    eq intersectNodeLists(M, NODE, (NODE' ; NODES), VOS) 
        = intersect(M, NODE, NODE', VOS, 0) ; intersectNodeLists(M, NODE, NODES, VOS)   .

    --- Get the intersection nodes between two nodes
    op intersect : Module Node Node VariantOptionSet Nat -> NodeList .
    eq intersect(M, {ID : term: T, ctr: CTR, NATTRS}, {ID' : term: T', ctr: CTR', NATTRS'}, VOS, UCOUNT)
        = if metaVariantDisjointUnify(M, T =? T', empty, '@, VOS, UCOUNT) :: UnificationTriple
          then
            buildIntersectionNode(T, T', CTR, CTR', metaVariantDisjointUnify(M, T =? T', empty, '@, VOS, UCOUNT)) ;
            intersect(M, {ID : term: T, ctr: CTR, NATTRS}, {ID' : term: T', ctr: CTR', NATTRS'}, VOS, s(UCOUNT))
          else 
            nil 
          fi .

    --- Rebuild parents using a ParentNodeList output
    op rebuildParents : ParentNodeList -> NodeList .
    eq rebuildParents(noParents) = nil .
    eq rebuildParents([ ID, T, CTR, ACSB, 0 ], PARENTS) 
        = {ID : term: T, ctr: CTR, acsub: ACSB, ndepth: 0, ntype: iNode} ; rebuildParents(PARENTS) .

    --- Rebuild children using a ChildNodeList output
    op rebuildChildren : ChildNodeList -> NodeList .
    eq rebuildChildren(noChildren) = nil .
    eq rebuildChildren([ ID, PID, T, CTR, RL, SB, ACSB, MLIST, DEPTH ], CHILDREN)
        = {ID : pid: PID, term: T, ctr: CTR, rule: RL, sub: SB, acsub: ACSB, match: noMatch, ndepth: DEPTH, ntype: gNode, fold: false} .
    eq rebuildChildren([ ID, T, CTR, ACSB, MLIST, DEPTH ], CHILDREN)
        = {ID : term: T, ctr: CTR, acsub: ACSB, match: noMatch, ndepth: DEPTH, ntype: sNode, fold: false} .

    op varAbsNode : Module ChildNode Term Variable -> Node .
    eq varAbsNode(M, [ ID, PID, T, CTR, RL, SB, ACSB, MLIST, DEPTH ], T', V)
        = {ID : pid: PID, 
           term:
            varAbs(M, T, T', V),
           ctr:
            ('_/\_[varAbs(M, CTR, T', V), '_=_[V, T']]),
           rule: RL, sub: SB, acsub: ACSB, 
           match: noMatch, ndepth: DEPTH, ntype: iNode, fold: false} .

    eq varAbsNode(M, [ ID, T, CTR, ACSB, MLIST, DEPTH ], T', V)
        = {ID : 
           term:
            varAbs(M, T, T', V),
           ctr:
            ('_/\_[varAbs(M, CTR, T', V), '_=_[V, T']]),
           acsub: ACSB, match: noMatch, 
           ndepth: DEPTH, ntype: sNode, fold: false} .

    --- Abstract a subterm from term (variable abstraction)
    op varAbsNode : Module ChildNode Term Variable -> Node .
    eq varAbsNode(M, [ ID, PID, T, CTR, RL, SB, ACSB, MLIST, DEPTH ], T', V)
        = {ID : pid: PID, 
           term:
            varAbs(M, T, T', V),
           ctr:
            ('_/\_[varAbs(M, CTR, T', V), '_=_[V, T']]),
           rule: RL, sub: SB, acsub: ACSB, 
           match: noMatch, ndepth: DEPTH, ntype: iNode, fold: false} .

    eq varAbsNode(M, [ ID, T, CTR, ACSB, MLIST, DEPTH ], T', V)
        = {ID : 
           term:
            varAbs(M, T, T', V),
           ctr:
            ('_/\_[varAbs(M, CTR, T', V), '_=_[V, T']]),
           acsub: ACSB, match: noMatch, 
           ndepth: DEPTH, ntype: sNode, fold: false} .
           
    op varAbs : Module TermList Term Variable -> Term .
    eq varAbs(M, (empty).TermList, T', V) = (empty).TermList .
    eq varAbs(M, '_/\_[NTL, NTL'], T'', V) = '_/\_[varAbs(M, NTL, T'', V), varAbs(M, NTL', T'', V)] .
    eq varAbs(M, F[NTL], T', V) = if F[NTL] == T' then V else F[varAbs(M, NTL, T', V)] fi . 
    eq varAbs(M, (T,NTL), T', V) = if T == T' then (V, varAbs(M, NTL, T', V)) else (T, varAbs(M, NTL, T', V)) fi .   
    eq varAbs(M, T, T', V) = if T == T' then V else T fi [owise] .          

    --- Add constants to a Module
    op addConstToMod : Module TermSet -> Module .
    eq addConstToMod(mod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endm, TS)
                = mod MOD is IL sorts SS . SUBSS (OPS addConstToMod'(TS)) MBS EQS RLS endm .
    eq addConstToMod(th MOD is IL sorts SS . SUBSS OPS MBS EQS RLS endth, TS)
                = th MOD is IL sorts SS . SUBSS (OPS addConstToMod'(TS)) MBS EQS RLS endth . 
    eq addConstToMod(smod MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsm, TS)
                = smod MOD is IL sorts SS . SUBSS (OPS addConstToMod'(TS)) MBS EQS RLS STTS STTD endsm .
    eq addConstToMod(sth MOD is IL sorts SS . SUBSS OPS MBS EQS RLS STTS STTD endsth, TS)
                = sth MOD is IL sorts SS . SUBSS (OPS addConstToMod'(TS)) MBS EQS RLS STTS STTD endsth .

    op addConstToMod' : TermSet -> OpDeclSet .
    eq addConstToMod'(mt) = none .
    eq addConstToMod'(C ;; TS) = (op getName(C) : nil -> getType(C) [ ctor ] .) addConstToMod'(TS) .

    op applySubToNode : Module Node Substitution Nat -> Node .
    eq applySubToNode(M, {ID : term: T, ctr: CTR, sub: SB, acsub: ACSB, NATTRS}, SB', IDCOUNT)
        = {IDCOUNT : 
           term: getTerm(metaReduce(M, applySub(T, SB'))), 
           ctr: reduceCtr(M, getTerm(metaReduce(M, applySub(CTR, SB')))), 
           sub: reduceSub(M, applySub(SB, SB')), 
           acsub: reduceSub(M, applySub(ACSB, SB')), 
           NATTRS} .
    eq applySubToNode(M, {ID : term: T, ctr: CTR, acsub: SB, NATTRS}, SB', IDCOUNT)
        = {IDCOUNT : 
           term: getTerm(metaReduce(M, applySub(T, SB'))), 
           ctr: reduceCtr(M, applySub(CTR, SB')), 
           acsub: reduceSub(M, applySub(SB, SB')), NATTRS} .

    op replaceTermInNode  : Term Term Node -> Node .
    eq replaceTermInNode(T, T, NODE) = NODE .
    eq replaceTermInNode(T, T', {ID : term: T'', ctr: CTR, acsub: ACSB, sub: SB, NATTRS}) 
        = {ID : term: replaceSubTerm(T, T', T''), ctr: replaceSubTerm(T, T', CTR), acsub: replaceSubTerm(T, T', ACSB), sub: replaceSubTerm(T, T', SB), NATTRS} .
    eq replaceTermInNode(T, T', {ID : term: T'', ctr: CTR, acsub: ACSB, NATTRS}) 
        = {ID : term: replaceSubTerm(T, T', T''), ctr: replaceSubTerm(T, T', CTR), acsub: replaceSubTerm(T, T', ACSB), NATTRS} [owise] .

    op replaceSubTerm : Term Term TermList -> TermList .
    eq replaceSubTerm(T, T', empty) = empty .
    eq replaceSubTerm(T, T', T) = T' .
    eq replaceSubTerm(T, T', F[TL]) = F[replaceSubTerm(T, T', TL)] [owise] .
    eq replaceSubTerm(T, T', (T, TL)) = (T', replaceSubTerm(T, T', TL)) .
    eq replaceSubTerm(T, T', (T'', NTL)) = (replaceSubTerm(T, T', T''), replaceSubTerm(T, T', NTL)) [owise] .
    eq replaceSubTerm(T, T', T'') = T'' [owise] .

    op replaceSubTerm : Term Term Substitution -> Substitution .
    eq replaceSubTerm(T, T', (none).Substitution) = none .
    eq replaceSubTerm(T, T', V <- T'' ; SB) = V <- replaceSubTerm(T, T', T'') ; replaceSubTerm(T, T', SB) .

    op applyMetaXMatchT : Module Node Term Variable Context TermSet Nat Qid -> Node .
    eq applyMetaXMatchT(M, {ID : term: T, ctr: CTR, NATTRS}, T', V, CTX, TS, IDCOUNT, 't)
        = {IDCOUNT : 
           term: getTerm(metaReduce(M, replaceHole(unfreeze(CTX, TS), V))), 
           ctr: reduceCtr(M,'_/\_[CTR, '_=_[V, T']]),
           NATTRS} .
    eq applyMetaXMatchT(M, {ID : ctr: CTR, NATTRS}, T', V, CTX, TS, IDCOUNT, 'c)
        = {IDCOUNT : 
           ctr: getTerm(metaReduce(M, '_/\_[replaceHole(unfreeze(CTX, TS), V), '_=_[V, T']])),
           NATTRS} .

    op reduceCtr : Module Term -> Term .
    eq reduceCtr(M, T) = removeTrueCtr(trivialCtrTrue(reduceCtr'(M, T))) .

    op reduceCtr' : Module TermList -> Term .
    eq reduceCtr'(M, '_/\_[T, NTL]) = '_/\_[reduceCtr'(M, T), reduceCtr'(M, NTL)] .
    eq reduceCtr'(M, '_=_[T, T']) = '_=_[reduceCtr'(M, T), reduceCtr'(M, T')] .
    eq reduceCtr'(M, (T, NTL)) = (reduceCtr'(M, T), reduceCtr'(M, NTL)) .
    eq reduceCtr'(M, T) = getTerm(metaReduce(M, T)) [owise] .

    op trivialCtrTrue : TermList -> Term .
    eq trivialCtrTrue('_/\_[T, NTL]) = '_/\_[trivialCtrTrue(T), trivialCtrTrue(NTL)] .
    eq trivialCtrTrue('_=_[T, T]) = 'true.NuITP-Bool .
    eq trivialCtrTrue((T, NTL)) = (trivialCtrTrue(T), trivialCtrTrue(NTL)) .
    eq trivialCtrTrue(T) = T [owise] .

    op removeTrueCtr : TermList -> Term .
    eq removeTrueCtr('_/\_[TL, 'true.NuITP-Bool, TL']) = removeTrueCtr('_/\_[TL, TL']) .
    eq removeTrueCtr('_/\_[T, NTL]) = '_/\_[removeTrueCtr(T), removeTrueCtr(NTL)] [owise] .
    eq removeTrueCtr('_/\_[T]) = removeTrueCtr(T) .
    eq removeTrueCtr((T, NTL)) = (removeTrueCtr(T), removeTrueCtr(NTL)) .
    eq removeTrueCtr(T) = T [owise] .

    op reduceSub : Module Substitution -> Substitution .
    eq reduceSub(M, (none).Substitution) = (none).Substitution .
    eq reduceSub(M, (V <- T ; SB)) = V <- getTerm(metaReduce(M, T)) ; reduceSub(M, SB) .

    op isSubsumed : Module ChildNode Term VariantOptionSet TermSet -> Bool .
    eq isSubsumed(M, [ ID, PID, T, CTR, RL, SB, ACSB, MLIST, N ], '_|_[T', CTR'], VOS, LEMMAS) = isSubsumed'(checkNodeSubsumption(M, rebuildChildren([ ID, PID, T, CTR, RL, SB, ACSB, MLIST, N ]), {0 : term: T', ctr: CTR'}, VOS, LEMMAS, 0)) .
    eq isSubsumed(M, CHILD, T, VOS, LEMMAS) = false [owise] .

    op isSubsumed' : Node -> Bool .
    eq isSubsumed'({ID : fold: true, NATTRS}) = true .
    eq isSubsumed'(NODE) = false [owise] .

    op keepTermsIn : TermList TermList -> TermList .
    eq keepTermsIn((TL, T, TL'), (TL'', T, TL''')) = T, keepTermsIn((TL, TL'), (TL'', T, TL''')) .
    eq keepTermsIn(TL, TL') = empty [owise] .

    op subtractTerms : TermList TermList -> TermList .
    eq subtractTerms((TL, T, TL'), (TL'', T, TL''')) = subtractTerms((TL, TL'), (TL'', TL''')) .
    eq subtractTerms(TL', TL) = TL' [owise] .

    op QLtoNL : QidList -> NatList .
    eq QLtoNL(nil) = nil .
    eq QLtoNL(Q) = rat(string(Q),10) . 
    eq QLtoNL((Q QL)) = rat(string(Q),10) QLtoNL(QL) . 

    op selectChildren : ChildNodeList NatList -> ChildNodeList .
    eq selectChildren(CHILDREN, nil) = noChildren .
    eq selectChildren(noChildren, NL) = noChildren .
    eq selectChildren((CHILDREN, [ ID, PID, T, CTR, RL, SB, ACSB, MLIST, N ], CHILDREN'), (NL ID NL'))
        = ([ ID, PID, T, CTR, RL, SB, ACSB, MLIST, N ], selectChildren((CHILDREN, CHILDREN'), (NL NL'))) .

    op rmvChildren : ChildNodeList NatList -> ChildNodeList .
    eq rmvChildren((CHILDREN, [ ID, PID, T, CTR, RL, SB, ACSB, MLIST, N ], CHILDREN'), (NL ID NL'))
        = rmvChildren((CHILDREN, CHILDREN'), (NL NL')) .
    eq rmvChildren(CHILDREN, NL) = CHILDREN [owise] .

    op reorderNodes : NodeList -> NodeList .
    eq reorderNodes(NODES ; {ID : NATTRS} ; NODES' ; {ID' : NATTRS'} ; NODES'')
        = if (ID > ID')
          then reorderNodes(NODES ; {ID' : NATTRS'} ; NODES' ; {ID : NATTRS} ; NODES'')
          else (NODES ; {ID : NATTRS} ; NODES' ; {ID' : NATTRS'} ; NODES'')
          fi .
    eq reorderNodes(NODES) = NODES [owise] . 
endm 

mod CHECK-INVARIANT is
    pr DM-CHECK-CORE .

    var M : Module .
    var NTL : NeTermList .
    var VOS : VariantOptionSet .
    var LEMMAS : TermSet .
    vars N ID PID DEPTH DEPTH' NDEPTH  VCOUNT IDCOUNT : Nat .
    var NATTRS : AttributeSet .
    var SATTRS : AttributeSet .
    vars NODES NODES' NODES'' : NodeList .
    var PARENTS : ParentNodeList .
    var CHILDREN : ChildNodeList .
    vars T T' CTR : Term .
    vars ACSB SB : Substitution .
    var RL : Qid .
    var MLIST : MatcherList .
    var OUTPUT : DMCOutput .

    --- Process the output for the check invariants command
    op outputInv : NodeList -> DMCOutput .
    eq outputInv(NODES) = outputInv'(noParents || noChildren, NODES) .

    op outputInv' : DMCOutput NodeList -> DMCOutput .
    eq outputInv'(OUTPUT, nil) = OUTPUT .
    eq outputInv'((PARENTS || CHILDREN), ({ID : term: T, ctr: CTR, acsub: ACSB, ntype: iNode, ndepth: 0} ; NODES))
        = outputInv'((PARENTS , [ID, T, CTR, ACSB, 0] || CHILDREN), NODES) .
    eq outputInv'((PARENTS || CHILDREN), ({ID : fold: true, NATTRS} ; NODES))
        = outputInv'((PARENTS || CHILDREN), NODES) .
    eq outputInv'((PARENTS || CHILDREN), ({ID : fold: false, pid: PID, term: T, ctr: CTR, rule: RL, sub: SB, acsub: ACSB, match: MLIST, ntype: gNode, ndepth: N, NATTRS} ; NODES))
        = outputInv'((PARENTS || CHILDREN, [ID, PID, T, CTR, RL, SB, ACSB, MLIST, N]), NODES) .

    --- Initialize the check invariants command
    op checkInvariant : Module NeTermList TermSet -> DMCOutput .
    eq checkInvariant(M, NTL, LEMMAS)
        = nextLevel(< mod: M, prev: nil, curr: checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS), 
                           next: nil, depth: 1, cdepth: 0, vos: none, lemmas: LEMMAS, 
                           idcount: (1 + countNodes(checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS))), 
                           vcount: (1 + countNodeVars(checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS))) >) .

    op checkInvariant : Module NeTermList TermSet Nat -> DMCOutput .
    eq checkInvariant(M, NTL, LEMMAS, DEPTH)
        = nextLevel(< mod: M, prev: nil, curr: checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS), 
                           next: nil, depth: DEPTH, cdepth: 0, vos: none, lemmas: LEMMAS, 
                           idcount: (1 + countNodes(checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS))), 
                           vcount: (1 + countNodeVars(checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS))) >) .

    op checkInvariant : Module NeTermList VariantOptionSet TermSet -> DMCOutput .
    eq checkInvariant(M, NTL, VOS, LEMMAS)
        = nextLevel(< mod: M, prev: nil, curr: checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS), 
                           next: nil, depth: 1, cdepth: 0, vos: VOS, lemmas: LEMMAS, 
                           idcount: (1 + countNodes(checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS))), 
                           vcount: (1 + countNodeVars(checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS))) >) .

    op checkInvariant : Module NeTermList VariantOptionSet TermSet Nat -> DMCOutput .
    eq checkInvariant(M, NTL, VOS, LEMMAS, DEPTH)
        = nextLevel(< mod: M, prev: nil, curr: checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS), 
                           next: nil, depth: DEPTH, cdepth: 0, vos: VOS, lemmas: LEMMAS, 
                           idcount: (1 + countNodes(checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS))), 
                           vcount: (1 + countNodeVars(checkConstraints(M, initNodes(M, NTL, 1, 1), LEMMAS))) >) .

    --- Generate the next level of the search space
    op nextLevel : DMCState -> DMCOutput .
    eq nextLevel(< mod: M, vos: VOS, depth: DEPTH, cdepth: DEPTH', prev: NODES, curr: NODES', next: nil, idcount: IDCOUNT, vcount: VCOUNT, SATTRS >)
        = if DEPTH == 0 or-else DEPTH' < DEPTH
          then
            checkNewConstraints(< mod: M, vos: VOS, depth: DEPTH, cdepth: s(DEPTH'), prev: (NODES ; NODES'), curr: nil, 
                              next: renameNodes(deployChildren(M, VOS, NODES', IDCOUNT), VCOUNT), 
                              idcount: (IDCOUNT + countNodes(deployChildren(M, VOS, NODES', IDCOUNT))),
                              vcount: (VCOUNT + countNodeVars(renameNodes(deployChildren(M, VOS, NODES', IDCOUNT), VCOUNT))), SATTRS >)
          else   
            outputInv(NODES ; NODES')
          fi .

    --- Check the constraints of new states
    op checkNewConstraints : DMCState -> DMCOutput .
    eq checkNewConstraints(< prev: NODES, next: nil, SATTRS >) 
        = outputInv(NODES) .
    eq checkNewConstraints(< mod: M, next: NODES, lemmas: LEMMAS, SATTRS >) 
        = checkFolding(< mod: M, next: checkConstraints(M, NODES, LEMMAS), lemmas: LEMMAS, SATTRS >) [owise] .

    --- Check folding for new states
    op checkFolding : DMCState -> DMCOutput .
    eq checkFolding(< prev: NODES, next: nil, SATTRS >) 
        = outputInv(NODES) .
    eq checkFolding(< mod: M, vos: VOS, lemmas: LEMMAS, prev: NODES, curr: nil, next: NODES', SATTRS >) 
        = nextLevel(< mod: M, vos: VOS, lemmas: LEMMAS, prev: NODES, 
                      curr: checkSubsumption(M, NODES', NODES, VOS, LEMMAS), 
                      next: nil, SATTRS >) [owise] .
endm 

mod GEN-INVARIANT is
    pr CHECK-INVARIANT .

    var M : Module .
    var NTL NTL' : NeTermList .
    vars T CTR : Term .
    var TL TL' TL'' TL''' : TermList .
    var LEMMAS : TermSet .
    var DEPTH IDCOUNT VCOUNT : Nat .
    var VOS : VariantOptionSet .
    var NODES : NodeList .

    --- Initialize the check invariants command
    op genInvariant : Module NeTermList TermSet -> DMCOutput .
    eq genInvariant(M, NTL, LEMMAS) = checkInvariant(M, NTL, LEMMAS) .

    op genInvariant : Module NeTermList TermSet Nat -> DMCOutput .
    eq genInvariant(M, NTL, LEMMAS, DEPTH) = checkInvariant(M, NTL, LEMMAS, DEPTH) .

    op genInvariant : Module NeTermList VariantOptionSet TermSet -> DMCOutput .
    eq genInvariant(M, NTL, VOS, LEMMAS) = checkInvariant(M, NTL, VOS, LEMMAS) .

    op genInvariant : Module NeTermList VariantOptionSet TermSet Nat -> DMCOutput .
    eq genInvariant(M, NTL, VOS, LEMMAS, DEPTH) = checkInvariant(M, NTL, VOS, LEMMAS, DEPTH) .

    op genInvariant : Module NeTermList NeTermList TermSet -> DMCOutput .
    eq genInvariant(M, NTL, NTL', LEMMAS)
        = genInvariant'(M, initNodes(M, keepTermsIn(NTL, NTL'), 1, 1), subtractTerms(NTL', NTL), LEMMAS, 
                           (1 + countNodes(initNodes(M, keepTermsIn(NTL, NTL'), 1, 1))),
                           (1 + countNodeVars(initNodes(M, keepTermsIn(NTL, NTL'), 1, 1)))) .

    op genInvariant' : Module NodeList NeTermList TermSet Nat Nat -> DMCOutput .
    eq genInvariant'(M, NODES, NTL, LEMMAS, IDCOUNT, VCOUNT)
        = nextLevel(< mod: M, prev: NODES, curr: checkConstraints(M, initNodes(M, NTL, IDCOUNT, VCOUNT), LEMMAS), 
                      next: nil, depth: 1, cdepth: 0, vos: none, lemmas: LEMMAS, 
                      idcount: (IDCOUNT + countNodes(checkConstraints(M, initNodes(M, NTL, IDCOUNT, VCOUNT), LEMMAS))), 
                      vcount: (VCOUNT + countNodeVars(checkConstraints(M, initNodes(M, NTL, IDCOUNT, VCOUNT), LEMMAS))) >) .
endm

mod CHECK-SUBSUMED is
    pr DM-CHECK-CORE .

    var M : Module .
    vars NTL NTL' : NeTermList .
    var VOS : VariantOptionSet .
    var LEMMAS : TermSet .
    var NODES : NodeList .
    vars ID IDCOUNT VCOUNT : Nat .
    var SATTRS : AttributeSet .
    var PARENTS : ParentNodeList .
    var CHILDREN : ChildNodeList .
    vars T T' CTR : Term .
    var V : Variable .
    var ACSB : Substitution .
    var NATTRS : AttributeSet .
    var MLIST : MatcherList .
    var OUTPUT : DMCOutput .

    --- Process the output for the subsumed command
    op outputSub : NodeList -> DMCOutput .
    eq outputSub(NODES) = outputSub'(noParents || noChildren, NODES) .

    op outputSub' : DMCOutput NodeList -> DMCOutput .
    eq outputSub'(OUTPUT, nil) = OUTPUT .
    eq outputSub'((PARENTS || CHILDREN), ({ID : term: T, ctr: CTR, acsub: ACSB, ntype: iNode, ndepth: 0} ; NODES))
        = outputSub'((PARENTS, [ID, T, CTR, ACSB, 0] || CHILDREN), NODES) .
    eq outputSub'((PARENTS || CHILDREN), ({ID : fold: true, NATTRS} ; NODES))
        = outputSub'((PARENTS || CHILDREN), NODES) .
    eq outputSub'((PARENTS || CHILDREN), ({ID : fold: false, term: T, ctr: CTR, acsub: ACSB, match: MLIST, ntype: sNode, ndepth: 0} ; NODES))
        = outputSub'((PARENTS || CHILDREN, [ID, T, CTR, ACSB, MLIST, 0]), NODES) .

    --- Initialize the check subsumed command
    op checkSubsumed : Module NeTermList NeTermList TermSet -> DMCOutput .
    eq checkSubsumed(M, NTL, NTL', LEMMAS)
        = checkSubsumed'(< mod: M, vos: none, lemmas: LEMMAS, 
                           init: checkConstraints(M, initNodes(M, NTL', 1, 1), LEMMAS), 
                           idcount: (1 + countNodes(checkConstraints(M, initNodes(M, NTL', 1, 1), LEMMAS))), 
                           vcount: (1 + countNodeVars(checkConstraints(M, initNodes(M, NTL', 1, 1), LEMMAS))) >,
                           NTL) .

    op checkSubsumed : Module NeTermList NeTermList VariantOptionSet TermSet -> DMCOutput .
    eq checkSubsumed(M, NTL, NTL', VOS, LEMMAS)
        = checkSubsumed'(< mod: M, vos: VOS, lemmas: LEMMAS, 
                           init: checkConstraints(M, initNodes(M, NTL', 1, 1), LEMMAS), 
                           idcount: (1 + countNodes(checkConstraints(M, initNodes(M, NTL', 1, 1), LEMMAS))), 
                           vcount: (1 + countNodeVars(checkConstraints(M, initNodes(M, NTL', 1, 1), LEMMAS))) >,
                           NTL) .

    --- Initialize the rest of states and check subsumption
    op checkSubsumed' : DMCState NeTermList -> DMCOutput .
    eq checkSubsumed'(< mod: M, vos: VOS, lemmas: LEMMAS, init: NODES, idcount: IDCOUNT, vcount: VCOUNT, SATTRS >, NTL)
        = outputSub( NODES ; checkSubsumption(M, initNodes'(M, NTL, IDCOUNT, VCOUNT), NODES, VOS, LEMMAS)) .

endm

mod CHECK-INTERSECTION is
    pr DM-CHECK-CORE .

    var M : Module .
    vars NTL NTL' : NeTermList .
    var VOS : VariantOptionSet .
    var LEMMAS : TermSet .
    var SATTRS : AttributeSet .
    vars ID IDCOUNT : Nat .
    vars NODES NODES' NODES'' : NodeList .
    vars T T' CTR : Term .
    vars LSB RSB ACSB : Substitution .
    var OUTPUT : DMCOutput .
    var PARENTS : ParentNodeList .
    var CHILDREN : ChildNodeList .

    --- Process the output for the intersection command
    op outputInt : NodeList -> DMCOutput .
    eq outputInt(NODES) = outputInt'(noParents || noChildren, NODES) .

    op outputInt' : DMCOutput NodeList -> DMCOutput .
    eq outputInt'(OUTPUT, nil) = OUTPUT .
    eq outputInt'(PARENTS || CHILDREN, {ID : term: T, ctr: CTR, acsub: ACSB, ndepth: 0, ntype: iNode} ; NODES) = 
        outputInt'((PARENTS, [ID, T, CTR, ACSB, 0]) || CHILDREN, NODES) .
    eq outputInt'(PARENTS || CHILDREN, {ID : lterm: T, rterm: T', ctr: CTR, lsub: LSB, rsub: RSB, ntype: itNode} ; NODES) = 
        outputInt'(PARENTS || (CHILDREN, [ID, applySub(T, LSB), T, T', CTR, LSB, RSB]), NODES) .
    eq outputInt'(PARENTS || CHILDREN, {ID : lterm: T, rterm: T', ctr: CTR, lsub: LSB, rsub: RSB, ntype: itNode} ; NODES) = 
        outputInt'(PARENTS || (CHILDREN, [ID, applySub(T, LSB), T, T', CTR, LSB, RSB]), NODES) .

    --- Check the intersection between two list of pair terms
    op checkIntersection : Module NeTermList NeTermList TermSet -> DMCOutput .
    eq checkIntersection(M, NTL, NTL', LEMMAS)
        = checkIntersection'(< mod: M, vos: none, lemmas: LEMMAS, 
                               init: checkConstraints(M, initNodes''(M, NTL, 1), LEMMAS),
                               idcount: (1 + countNodes(checkConstraints(M, initNodes''(M, NTL, 1), LEMMAS))) >, NTL') .

    op checkIntersection : Module NeTermList NeTermList VariantOptionSet TermSet -> DMCOutput .
    eq checkIntersection(M, NTL, NTL', VOS, LEMMAS)
        = checkIntersection'(< mod: M, vos: VOS, lemmas: LEMMAS, 
                               init: checkConstraints(M, initNodes''(M, NTL, 1), LEMMAS),
                               idcount: (1 + countNodes(checkConstraints(M, initNodes''(M, NTL, 1), LEMMAS))) >, NTL') .

    op checkIntersection' : DMCState NeTermList -> DMCOutput .
    eq checkIntersection'(< SATTRS, mod: M, lemmas: LEMMAS, idcount: IDCOUNT >, NTL)
        = getIntersection(< SATTRS, mod: M, lemmas: LEMMAS, 
                            init': checkConstraints(M, initNodes''(M, NTL, IDCOUNT), LEMMAS), 
                            idcount: (IDCOUNT + countNodes(checkConstraints(M, initNodes''(M, NTL, IDCOUNT), LEMMAS))) >) .

    op getIntersection : DMCState -> DMCOutput .
    eq getIntersection(< mod: M, vos: VOS, lemmas: LEMMAS, init: NODES, init': NODES', idcount: IDCOUNT >)
        = checkIntersectionConstraints(< mod: M, vos: VOS, lemmas: LEMMAS, init: NODES, init': NODES',
                                         inter: intersectLists(M, NODES, NODES', VOS, IDCOUNT),
                                         idcount: (IDCOUNT + countNodes(intersectLists(M, NODES, NODES', VOS, IDCOUNT))) >) .
    
    op checkIntersectionConstraints : DMCState -> DMCOutput .
    eq checkIntersectionConstraints(< SATTRS, mod: M, lemmas: LEMMAS, init: NODES, init': NODES', inter: NODES'' >)
        = outputInt(NODES ; NODES' ; checkConstraints(M, NODES'', LEMMAS)) .
endm

mod AUX-COMMANDS is
    pr DM-CHECK-CORE .

    var M : Module .
    var PARENTS : ParentNodeList .
    var CHILD : ChildNode .
    var CHILDREN CHILDREN' : ChildNodeList .
    var V : Variable .
    var VOS : VariantOptionSet .
    vars GENSET LEMMAS : TermSet .
    vars ID ID' PID IDCOUNT VCOUNT N DEPTH : Nat .
    var NZN : NzNat .
    vars T T' CTR CTR' : Term .
    var TL : TermList .
    vars SB SB' ACSB : Substitution .
    var OUTPUT : DMCOutput .
    var RL : Qid .
    var MLIST : MatcherList .
    vars SATTRS NATTRS NATTRS' : AttributeSet .
    vars NODES NODES' NODES'' : NodeList .
    var NODE : Node .
    var NTS : NeTermSet .
    var B : Bool .
    vars Q Q' : Qid .
    vars QL QL' : QidList .
    var PARENT : Parent .
    var TP : Type .
    var CTX : Context .
    var NTL : NeTermList .

    --- Check folding after an auxiliary command
    op checkAuxCommand : DMCState Nat -> ChildNodeList .
    eq checkAuxCommand(< next: nil, SATTRS >, VCOUNT) 
        = outputAuxCommand(nil) .
    eq checkAuxCommand(< mod: M, vos: VOS, lemmas: LEMMAS, init: NODES, next: NODES', SATTRS >, VCOUNT)
        = outputAuxCommand(checkSubsumption(M, renameNodes(NODES', VCOUNT), NODES, VOS, LEMMAS)) .

    --- Process the output for the auxiliary commands
    op outputAuxCommand : NodeList -> ChildNodeList .
    eq outputAuxCommand(NODES) = outputAuxCommand'(reorderNodes(NODES)) .

    op outputAuxCommand' : NodeList -> ChildNodeList .
    eq outputAuxCommand'(nil) = noChildren .
    eq outputAuxCommand'({ID : fold: true, NATTRS} ; NODES) = outputAuxCommand'(NODES) .
    eq outputAuxCommand'({ID : fold: false, pid: PID, term: T, ctr: CTR, rule: RL, sub: SB, acsub: ACSB, match: MLIST, ndepth: N, ntype: gNode, NATTRS} ; NODES)
        = [ ID, PID, T, CTR, RL, SB, ACSB, MLIST, N ], outputAuxCommand'(NODES) .
    eq outputAuxCommand'({ID : fold: false, term: T, ctr: CTR, acsub: ACSB, match: MLIST, ndepth: N, ntype: sNode, NATTRS} ; NODES)
        = [ ID, T, CTR, ACSB, MLIST, 0 ], outputAuxCommand'(NODES) .

    --- CASE command
    op case : Module ParentNodeList ChildNode Variable TermSet Nat Nat VariantOptionSet TermSet -> ChildNodeList .
    eq case(M, PARENTS, CHILD, V, GENSET, IDCOUNT, VCOUNT, VOS, LEMMAS)
        = checkAuxCommand(< mod: M, vos: VOS, lemmas: LEMMAS, 
                            init: rebuildParents(PARENTS),
                            next: checkConstraints(M, genCaseChildren(M, rebuildChildren(CHILD), V, GENSET, IDCOUNT), LEMMAS) >, VCOUNT) .

    op genCaseChildren : Module Node Variable TermSet Nat -> NodeList .
    eq genCaseChildren(M, {ID : NATTRS}, V, T, N) 
        = applySubToNode(M, {ID : NATTRS}, V <- T, N) .
    eq genCaseChildren(M, {ID : NATTRS}, V, (T ;; NTS), N) 
        = applySubToNode(M, {ID : NATTRS}, V <- T, N) ; genCaseChildren(M, {ID : NATTRS}, V, NTS, N + 1) .

    --- Initialize the variable abstraction command
    sort VarAbsPair .
    op {_,_} : Nat ChildNodeList -> VarAbsPair .

    op variableAbstraction : Module ParentNodeList ChildNode Term Variable Nat Nat VariantOptionSet TermSet -> VarAbsPair .
    eq variableAbstraction(M, PARENTS, CHILD, T, V, IDCOUNT, VCOUNT, VOS, LEMMAS)
        = variableAbstraction'(rebuildChildren(CHILD), 
                               < mod: M, vos: VOS, lemmas: LEMMAS, 
                               init: rebuildParents(PARENTS),
                               next: checkConstraints(M, genVarAbsChildren(M, rebuildChildren(CHILD), T, V, IDCOUNT, 0, 't), LEMMAS) >, VCOUNT) .
    
    op variableAbstraction' : Node DMCState Nat -> VarAbsPair .
    eq variableAbstraction'({ID : NATTRS}, < next: NODES, SATTRS >, VCOUNT)
        = {ID, outputAuxCommand(renameNodes(NODES, VCOUNT))} .

    op genVarAbsChildren : Module Node Term Variable Nat Nat Qid -> NodeList .
    eq genVarAbsChildren(M, {ID : term: T, NATTRS}, T', V, IDCOUNT, N, 't)
        = if metaXmatch(addOps(M, freeze(getVars(T) ;; getVars(T'))), 
                        freeze(T'), freeze(T), nil, 0, unbounded, N) :: MatchPair
          then
            applyMetaXMatchT(M, {ID : term: T, NATTRS}, T', V, getContext(metaXmatch(addOps(M, freeze(getVars(T) ;; getVars(T'))), freeze(T'), freeze(T), nil, 0, unbounded, N)), (getVars(T) ;; getVars(T')), IDCOUNT, 't) ;
            genVarAbsChildren(M, {ID : term: T, NATTRS}, T', V, IDCOUNT + 1, N + 1, 't)
          else
            genVarAbsChildren(extModule(M), {ID : term: T, NATTRS}, T', V, IDCOUNT, N, 'c)
          fi .
    eq genVarAbsChildren(M, {ID : ctr: CTR, NATTRS}, T', V, IDCOUNT, N, 'c)
        = if metaXmatch(addOps(M, freeze(getVars(CTR) ;; getVars(T'))), 
                        freeze(T'), freeze(CTR), nil, 0, unbounded, N) :: MatchPair
          then
            applyMetaXMatchT(M, {ID : ctr: CTR, NATTRS}, T', V, getContext(metaXmatch(addOps(M, freeze(getVars(CTR) ;; getVars(T'))), freeze(T'), freeze(CTR), nil, 0, unbounded, N)), (getVars(CTR) ;; getVars(T')), IDCOUNT, 'c) ;
            genVarAbsChildren(M, {ID : ctr: CTR, NATTRS}, T', V, IDCOUNT + 1, N + 1, 'c)
          else
            nil
          fi .
    
    op applyVarAbs : Module ChildNode ParentNodeList VariantOptionSet TermSet -> ChildNodeList .
    eq applyVarAbs(M, CHILD, PARENTS, VOS, LEMMAS)
        = outputAuxCommand(checkSubsumption(M, rebuildChildren(CHILD), rebuildParents(PARENTS), VOS, LEMMAS)) .

    op getChildren : VarAbsPair -> ChildNodeList .
    eq getChildren({N, CHILDREN}) = CHILDREN .

    --- SUBSTITUTION command
    op subsCommand : Module ParentNodeList ChildNode Variable Term Nat VariantOptionSet TermSet -> ChildNodeList .
    eq subsCommand(M, PARENTS, CHILD, V, T', VCOUNT, VOS, LEMMAS)
        = checkAuxCommand(< mod: M, vos: VOS, lemmas: LEMMAS, 
                             init: rebuildParents(PARENTS),
                             next: checkConstraints(M, subsCommandChild(M, rebuildChildren(CHILD), V, T'), LEMMAS) >, VCOUNT) . 

    op subsCommandChild : Module Node Variable Term -> Node .
    eq subsCommandChild(M, {ID : NATTRS}, V, T) = applySubToNode(M, {ID : NATTRS}, (V <- T), ID) .

    --- VARIANT UNIFY command
    op vunify : Module ParentNodeList ChildNode Term Term Nat Nat VariantOptionSet TermSet  -> ChildNodeList .
    eq vunify(M, PARENTS, CHILD, T, T', IDCOUNT, VCOUNT, VOS, LEMMAS)
        = checkAuxCommand(< mod: M, vos: VOS, lemmas: LEMMAS, 
                            init: rebuildParents(PARENTS),
                            next: checkConstraints(M, genVUnifyChildren(M, rebuildChildren(CHILD), T, T', IDCOUNT, 0), LEMMAS) >, VCOUNT) .
    
    op genVUnifyChildren : Module Node Term Term Nat Nat -> NodeList .
    eq genVUnifyChildren(M, NODE, T, T', IDCOUNT, N)
        = if metaVariantUnify(M, T =? T', empty, '@, filter delay, N) :: UnificationPair
          then 
            applySubToNode(M, NODE, getSubstitution(metaVariantUnify(M, T =? T', empty, '@, filter delay, N)), IDCOUNT);
            genVUnifyChildren(M, NODE, T, T', IDCOUNT + 1, N + 1)
          else 
            nil
          fi .

    --- NARROWING command
    op narrow : Module ParentNodeList ChildNode Term Nat Nat VariantOptionSet TermSet  -> ChildNodeList .
    eq narrow(M, PARENTS, CHILD, T, IDCOUNT, VCOUNT, VOS, LEMMAS)
        = checkAuxCommand(< mod: M, vos: VOS, lemmas: LEMMAS, 
                            init: rebuildParents(PARENTS),
                            next: checkConstraints(M, genNarrowChildren(M, rebuildChildren(CHILD), T, IDCOUNT, 0), LEMMAS) >, VCOUNT) .

    op genNarrowChildren : Module Node Term Nat Nat -> NodeList .
    eq genNarrowChildren(M, NODE, T, IDCOUNT, N)
        = if metaNarrowingApply(transformMod(euR(M, T)), T, empty, '@, none, N) :: NarrowingApplyResult
          then
            applyNarrowingResult(M, NODE, T, metaNarrowingApply(transformMod(euR(M, T)), T, empty, '@, none, N), IDCOUNT);
            genNarrowChildren(M, NODE, T, IDCOUNT + 1, N + 1)
          else
            nil
          fi .

    op applyNarrowingResult : Module Node Term NarrowingApplyResult Nat -> Node .
    eq applyNarrowingResult(M, {ID : ctr: CTR, NATTRS}, T, {'_dmc>_[CTR', T'], TP, CTX, Q, SB, SB', Q'}, IDCOUNT) 
        = applySubToNode(M, replaceTermInNode(T, T', {ID : ctr: ('_/\_[CTR, buildCtr(CTR')]), NATTRS}), SB, IDCOUNT) .
    eq applyNarrowingResult(M, NODE, T, {T', TP, CTX, Q, SB, SB', Q'}, IDCOUNT) 
        = applySubToNode(M, replaceTermInNode(T, T', NODE), SB, IDCOUNT) [owise] .
        
    --- Output to inv (GENERATE NEXT LEVEL command)
    op genNextLevel : Module DMCOutput TermSet -> TermList .
    eq genNextLevel(M, (PARENTS || CHILDREN), LEMMAS)
        = rmvSubsumedPatterns(M, nodesToInv(PARENTS || CHILDREN), LEMMAS) .

    op nodesToInv : DMCOutput -> TermList .
    eq nodesToInv(noParents || noChildren) = empty .
    eq nodesToInv([ ID, T, CTR, ACSB, 0 ], PARENTS || CHILDREN)
        = '_|_[T, CTR], nodesToInv(PARENTS || CHILDREN) .
    eq nodesToInv(noParents || [ ID, PID, T, CTR, RL, SB, ACSB, MLIST, N ], CHILDREN)
        = '_|_[T, CTR], nodesToInv(noParents || CHILDREN) .

    --- GENERALIZE command
    op generalize : Module ParentNodeList ChildNodeList NeTermList Nat VariantOptionSet TermSet QidList -> ChildNodeList .
    eq generalize(M, PARENTS, CHILDREN, '_|_[T', CTR'], VCOUNT, VOS, LEMMAS, QL)
        = generalize'(< mod: M, vos: VOS, lemmas: LEMMAS, init: rebuildParents(PARENTS),
                        prev: rebuildChildren(rmvChildren(CHILDREN, QLtoNL(QL))),
                        next: checkConstraints(M, applyGeneralize(selectChildren(CHILDREN, QLtoNL(QL)), '_|_[T', CTR'], VCOUNT), LEMMAS) >) .
    
    op generalize' : DMCState -> ChildNodeList .
    eq generalize'(< next: nil, SATTRS >) 
        = outputAuxCommand(nil) .
    eq generalize'(< mod: M, vos: VOS, lemmas: LEMMAS, init: NODES, prev: NODES', next: NODES'', SATTRS >)
        = outputAuxCommand(NODES' ; checkSubsumption(M, NODES'', NODES, VOS, LEMMAS)) .

    op applyGeneralize : ChildNodeList NeTermList Nat -> NodeList .
    eq applyGeneralize(noChildren, TL, VCOUNT) = nil .
    eq applyGeneralize(([ ID, PID, T, CTR, RL, SB, ACSB, MLIST, N ], CHILDREN), '_|_[T', CTR'], VCOUNT)
        = rebuildChildren([ ID, PID, applySub(T', rename(getVars((T', CTR')), VCOUNT)), applySub(CTR', rename(getVars((T', CTR')), VCOUNT)), 'none, none, none, noMatch, N ]) ;
          applyGeneralize(CHILDREN, '_|_[T', CTR'], VCOUNT + countVars(getVars((T', CTR')))) .

    op split : Module ParentNodeList ChildNode Term Nat Nat VariantOptionSet TermSet  -> ChildNodeList .
    eq split(M, PARENTS, CHILD, T, IDCOUNT, VCOUNT, VOS, LEMMAS)
        = checkAuxCommand(< mod: M, vos: VOS, lemmas: LEMMAS, 
                            init: rebuildParents(PARENTS),
                            next: checkConstraints(M, splitPattern(M, rebuildChildren(CHILD), T, IDCOUNT), LEMMAS) >, VCOUNT) .

    op splitPattern : Module Node Term Nat -> NodeList .
    eq splitPattern(M, {ID : ctr: CTR, NATTRS}, T, IDCOUNT)
        = {IDCOUNT : ctr: getTerm(metaRewrite(extModule(setRls(M, none)), '_/\_[CTR,'_=_[T,'True.Bool]], unbounded)), NATTRS} ;
          {IDCOUNT + 1 : ctr: getTerm(metaRewrite(extModule(setRls(M, none)), '_/\_[CTR,'_=_[T,'False.Bool]], unbounded)), NATTRS} .
endm

mod DM-CHECK is
    pr CHECK-INVARIANT .
    pr GEN-INVARIANT .
    pr CHECK-SUBSUMED .
    pr CHECK-INTERSECTION .
    pr AUX-COMMANDS .
endm

mod DM-CHECK-DISJUNCTION is
    pr QID-LIST .
    pr TRUTH-VALUE .

    sorts Eq ConjEq ConstTerm Disjunction Bubble .
    subsort ConstTerm < Disjunction .
    subsorts Eq < ConjEq < Bool .
    
    op bubble : QidList -> Bubble [ special (id-hook Bubble (1 -1 `( `)) op-hook qidListSymbol (__ : QidList QidList ~> QidList) op-hook qidSymbol (<Qids> : ~> Qid) id-hook Exclude ( \/ /\ | = )) ] .

    op _\/_ : Disjunction Disjunction -> Disjunction [ ctor assoc prec 60 ] .
    op _|_ : Bubble Bool -> ConstTerm [ ctor prec 50 ] .
    op _=_ : Bubble Bubble -> Eq [ ctor prec 40 ] .
    op _/\_ : ConjEq ConjEq -> ConjEq [ ctor assoc prec 45 ] .
endm

mod DM-CHECK-STRING is
    pr DM-CHECK .
    pr LEXICAL .
    
    var M : Module .
    var Q RL : Qid .
    var NTL : NeTermList .
    var LEMMAS? : TermSet .
    var LEMMAS : NeTermSet .
    vars T T' T'' TERM CTR IMPLICATION CONSTRAINT LEMMA : Term .
    var TL : TermList .
    vars ID ID' PID MID N : Nat .
    var PROOF PROOF' : ProofState .
    var MATCH? : Substitution? .
    vars MATCH SB SB1 SB2 ACSB LSB RSB : Substitution .
    var NAR : NarrowingApplyResult .
    var V : Variable .
    var ML ML1 ML2 : MatcherList .
    var NML : NeMatcherList .
    var POS : String .
    var PARENTS : ParentNodeList .
    vars CHILDREN CHILDREN1 CHILDREN2 : ChildNodeList .
    var CHILD : ChildNode .

    --- Error Messages
    op errorMsg : Nat -> String .
    op errorMsg : Nat Nat -> String .
    eq errorMsg(0) = "\n\033[1;31m  Warning:\033[0m unexpected error.\n\n" .
    eq errorMsg(1) = "\n\033[1;31m  Warning:\033[0m module not loaded.\n\n" .
    eq errorMsg(2) = "\n\033[1;31m  Warning:\033[0m error while parsing invariant.\n\n" .
    eq errorMsg(3) = "\n\033[1;31m  Warning:\033[0m error while parsing command.\n\n" .
    eq errorMsg(4) = "\n\033[1;31m  Warning:\033[0m error while parsing lemma.\n\n" .
    eq errorMsg(5) = "\n\033[1;31m  Warning:\033[0m no previous result available.\n\n" .
    eq errorMsg(6) = "\n\033[1;31m  Warning:\033[0m no child nodes found.\n\n" .
    eq errorMsg(7) = "\n\033[1;31m  Warning:\033[0m no matcher found.\n\n" .
    eq errorMsg(8) = "\n\033[1;31m  Warning:\033[0m no lemma found.\n\n" .
    eq errorMsg(9) = "\n\033[1;31m  Warning:\033[0m command not available for intersection results.\n\n" .
    eq errorMsg(10) = "\n\033[1;31m  Warning:\033[0m error while parsing variable.\n\n" .
    eq errorMsg(11) = "\n\033[1;31m  Warning:\033[0m error while parsing generator set.\n\n" .
    eq errorMsg(12) = "\n\033[1;31m  Warning:\033[0m variable clash between generator set and child node.\n\n" .
    eq errorMsg(13) = "\n\033[1;31m  Warning:\033[0m error while parsing subterm.\n\n" .
    eq errorMsg(14) = "\n\033[1;31m  Warning:\033[0m variable clash between term and variable.\n\n" .
    eq errorMsg(15) = "\n\033[1;31m  Warning:\033[0m variable clash between term and substitution.\n\n" .
    eq errorMsg(16) = "\n\033[1;31m  Warning:\033[0m error while parsing left-hand unification term.\n\n" .
    eq errorMsg(17) = "\n\033[1;31m  Warning:\033[0m error while parsing right-hand unification term.\n\n" .
    eq errorMsg(18) = "\n\033[1;31m  Warning:\033[0m cannot apply narrowing to the selected operator.\n\n" .
    eq errorMsg(19) = "\n\033[1;31m  Warning:\033[0m subterm not found.\n\n" .
    eq errorMsg(20) = "\n\033[1;31m  Warning:\033[0m variable not found.\n\n" .
    eq errorMsg(21) = "\n\033[1;31m  Warning:\033[0m invalid pattern for generalization.\n\n" .
    eq errorMsg(22) = "\n\033[1;31m  Warning:\033[0m variable clash between terms or constraints.\n\n" .
    eq errorMsg(23) = "\n\033[1;31m  Warning:\033[0m command only available for check or generate ind-invariant results.\n\n" .
    eq errorMsg(24) = "\n\033[1;31m  Warning:\033[0m the expression to split must be of sort Bool.\n\n" .
    eq errorMsg(25) = "\n\033[1;31m  Warning:\033[0m all variables in the expression to split must appear in the selected pattern.\n\n" .
    eq errorMsg(26, 1) = "\n\033[1;31m  Warning:\033[0m a non-conditional rule does not include the narrowing label.\n\n" .
    eq errorMsg(26, N) = "\n\033[1;31m  Warning:\033[0m " + string(N, 10) + " non-conditional rules do not include the narrowing label.\n\n" [owise] .
    
    op helpText : -> String .
    eq helpText =
        ("\n\033[1;36m  DM-Check Commands\033[0m\n\n" +

        "  === Session ===\n" +
        "  quit / q                                              : exit the system\n" +
        "  set module <M> .                                      : activate a verification module\n\n" +

        "  === Inspection ===\n" +
        "  show module .                                         : show active module\n" +
        "  show lemmas .                                         : list current lemmas\n" +
        "  show last .                                           : show last result\n" +
        "  show obligations .                                    : show pending proof obligations\n\n" +

        "  === Verification ===\n" +
        "  check ind-invariant <φ> .                             : check inductive invariant\n" +
        "  generate ind-invariant <φ> .                          : generate inductive invariant automatically\n" +
        "  check φ1 subsumed by φ2 .                             : subset checking\n" +
        "  intersect φ1 with φ2 .                                : check intersection\n\n" +

        "  === Pattern Equivalence and Generalization ===\n" +
        "  case to <id> on <v> with <G> .                        : case split on generator set\n" +
        "  variable abstraction <term> with <variable> in <id> . : abstraction-based reasoning\n" +
        "  split <id> with <term> .                              : split case on boolean term\n" +
        "  select variable abstraction <n> .                     : select abstraction option\n" +
        "  variant unify <t1> =? <t2> in <id> .                  : unify and apply substitution\n" +
        "  narrowing <id> on <term> .                            : apply narrowing step\n" +
        "  substitution to <id> on <v> with <t> .                : apply substitution\n" +
        "  generalize <id> using <pattern> .                     : generalize constrained pattern\n\n" +

        "  === Marking Proof Steps ===\n" +
        "  add lemma <lemma> .                                   : introduce auxiliary lemma\n" +
        "  empty <id> of <parent-id> .                           : mark conditions of state as unsatisfiable\n" +
        "  lemma <id> of <parent-id> .                           : discharge using lemma\n" +
        "  contained <id> of <parent-id> .                       : mark state as subsumed by parent state\n\n"
        ) .

    op toString : Module TermList -> String .
    eq toString(M, 'true.NuITP-Bool) = "true" .
    eq toString(M, 'false.NuITP-Bool) = "false" .
    eq toString(M, TL) = toString'(M, TL) [ owise ] .

    op toString' : Module TermList -> String .
    eq toString'(M, (empty).TermList) = "" .
    eq toString'(M, T) = metaPrintToString(M, none, T, mixfix, none) .
    eq toString'(M, (T,NTL)) = metaPrintToString(M, none, T, mixfix, none) + "\n" + toString(M,NTL) .

    op toString : Module Substitution -> String .
    eq toString(M, (none).Substitution) = "  none" .
    eq toString(M, V <- T) = "  " + toString(M, V) + " --> " + toString(M, T) .
    eq toString(M, V <- T ; SB) = "  " + toString(M, V) + " --> " + toString(M, T) + "\n" + toString(M, SB) [ owise ] .

    op toStringParents : Module ParentNodeList -> String .
    eq toStringParents(M, noParents) = "" .
    eq toStringParents(M, [ ID, T, CTR, ACSB, 0 ]) = 
        "\nParent " + string(ID, 10) + 
        "\nTerm:\n  " + toString(M, T) + 
        "\nConstraint:\n  " + toString(M, CTR) 
        .
    eq toStringParents(M, ([ ID, T, CTR, ACSB, 0 ], PARENTS)) = toStringParents(M, [ ID, T, CTR, ACSB, 0 ]) + "\n" + toStringParents(M, PARENTS) .
    
    op toStringMatcherListInv : Module MatcherList Nat -> String .
    eq toStringMatcherListInv(M, noMatch, N) = "" .
    eq toStringMatcherListInv(M, (MID, MATCH, IMPLICATION, PROOF) ; ML, N) = "\nMatching parent #" + string(N, 10) + ": " + string(MID, 10) + "\nMatching substitution #" + string(N, 10) + ":\n" + toString(M, MATCH) + "\nNuITP implication #" + string(N, 10) + " (" + toStringProofState(PROOF) + "):\n" + toString(M, IMPLICATION) + toStringMatcherListInv(M, ML, N + 1) .

    op toStringMatcherListSub : Module MatcherList Nat -> String .
    eq toStringMatcherListSub(M, noMatch, N) = "" .
    eq toStringMatcherListSub(M, (MID, MATCH, IMPLICATION, PROOF) ; ML, N) = "\nNuITP implication (" + toStringProofState(PROOF) + "):\n  " + toString(M, IMPLICATION) + toStringMatcherListSub(M, ML, N + 1) .

    op toStringProofState : ProofState -> String .
    eq toStringProofState(sat) = "sat" .
    eq toStringProofState(open) = "open" .
    eq toStringProofState(unsat) = "unsat" .
    
    op toStringChildrenInv : Module ChildNodeList -> String .
    eq toStringChildrenInv(M, noChildren) = "" .
    eq toStringChildrenInv(M, [ ID, PID, T, CTR, RL, SB, ACSB, noMatch, N ]) = 
        "\nChild " + string(ID, 10) + " (Parent " + string(PID, 10) + ")" + 
        "\nTerm:\n  " + toString(M, T) +
        "\nRule: " + string(RL) + 
        "\nUnifier:\n" + toString(M, SB) +
        "\nMatching: no matching found" +
        "\nConstraint:\n  " + toString(M, CTR) .
        eq toStringChildrenInv(M, [ ID, PID, T, CTR, RL, SB, ACSB, NML, N ]) = 
        "\nChild " + string(ID, 10) + " (Parent " + string(PID, 10) + ")" + 
        "\nTerm:\n  " + toString(M, T) +
        "\nRule: " + string(RL) + 
        "\nUnifier:\n" + toString(M, SB) +
        toStringMatcherListInv(M, NML, 1) .
    eq toStringChildrenInv(M, noChildren) = "" .
    eq toStringChildrenInv(M, ([ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN)) = toStringChildrenInv(M, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ]) + "\n" + toStringChildrenInv(M, CHILDREN) .

    op toStringChildrenSub : Module ChildNodeList -> String .
    eq toStringChildrenSub(M, noChildren) = "" .
    eq toStringChildrenSub(M, [ ID, T, CTR, ACSB, noMatch, N ]) = 
        "\nTerm " + string(ID, 10) + ":\n  " + toString(M, T) +
        "\nMatching: no matching found" +
        "\nConstraint " + string(ID, 10) + ":\n  " + toString(M, CTR) .
    eq toStringChildrenSub(M, [ ID, T, CTR, ACSB, NML, N ]) =
        "\nTerm " + string(ID, 10) + ":\n  " + toString(M, T) +
        "\nConstraint " + string(ID, 10) + ":\n  " + toString(M, CTR) +
        toStringMatcherListSub(M, NML, 1) .
    eq toStringChildrenSub(M, noChildren) = "" .
    eq toStringChildrenSub(M, ([ ID, T, CTR, ACSB, ML, N ], CHILDREN)) = toStringChildrenSub(M, [ ID, T, CTR, ACSB, ML, N ]) + "\n" + toStringChildrenSub(M, CHILDREN) .
    
    op toStringChildrenInt : Module ChildNodeList -> String .
    eq toStringChildrenInt(M, noChildren) = "" .
    eq toStringChildrenInt(M, ([ ID, T, T', T'', CTR, LSB, RSB ], CHILDREN)) = 
        "\nIntersection Term:\n  " + toString(M, T'') + 
        "\nLeft Term:\n  " + toString(M, T) + 
        "\nLeft Substitution:\n" + toString(M, LSB) +
        "\nRight Term:\n  " + toString(M, T') + 
        "\nRight Substitution:\n" + toString(M, RSB) +
        "\nConstraint:\n  " + toString(M, CTR) + 
        "\n" + toStringChildrenInt(M, CHILDREN) .
    
    op toString : Module Qid -> String .
    eq toString(M, Q) = string(Q) .

    op toStringLemmas : Module TermSet -> String .
    eq toStringLemmas(M, mt) = "" .
    eq toStringLemmas(M, T) = "  " + toString(M, T) .
    eq toStringLemmas(M, (T ;; LEMMAS)) = "  " + toString(M, T) + "\n" + toStringLemmas(M, LEMMAS) .

    op toStringInv : Module DMCOutput TermSet String -> String .
    eq toStringInv(M, noParents || CHILDREN, LEMMAS?, POS) = errorMsg(0) .
    eq toStringInv(M, PARENTS || ([ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN), LEMMAS?, POS) = "\033[1;31m  Invariant could not be proved.\033[0m\n" + toStringParents(M, PARENTS) + "\n" + toStringChildrenInv(M, ([ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN)) .
    eq toStringInv(M, PARENTS || noChildren, mt, POS) = 
        if (POS == "")
        then "\033[1;32m  Invariant satisfied.\033[0m"
        else "\033[1;32m  Invariant satisfied with the following proof obligations:\033[0m\n\n" + POS
        fi .
    eq toStringInv(M, PARENTS || noChildren, LEMMAS, POS) = "\033[1;32m  Invariant satisfied with the following proof obligations:\033[0m\n\n" + toStringLemmas(M, LEMMAS) + (if (POS == "") then "" else "\n" + POS fi) .
    
    op toStringGen : Module DMCOutput TermSet String -> String .
    eq toStringGen(M, noParents || CHILDREN, LEMMAS?, POS) = errorMsg(0) .
    eq toStringGen(M, PARENTS || ([ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN), LEMMAS?, POS) = "\033[1;31m  Invariant could not be proved.\033[0m\n" + toStringParents(M, PARENTS) + "\n" + toStringChildrenInv(M, ([ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN)) .
    eq toStringGen(M, PARENTS || noChildren, mt, POS) = 
        if (POS == "")
        then "\033[1;32m  The following invariant is satisfied \033[0m\n\n" + parentsToInv(M, PARENTS)
        else "\033[1;32m  The following invariant is satisfied \033[0m\n\n" + parentsToInv(M, PARENTS) + "\n\n\033[1;32m    with the following proof obligations:\033[0m\n\n" + POS
        fi .
    eq toStringGen(M, PARENTS || noChildren, LEMMAS, POS) = "\033[1;32m  The following invariant is satisfied \033[0m\n\n" + parentsToInv(M, PARENTS) + "\n\n\033[1;32m    with the following proof obligations:\033[0m\n\n" + toStringLemmas(M, LEMMAS) + (if (POS == "") then "" else "\n" + POS fi) .
    
    op parentsToInv : Module ParentNodeList -> String .
    eq parentsToInv(M, noParents) = "" .
    eq parentsToInv(M, [ ID, T, CTR, ACSB, 0 ]) = 
        "  ((" + toString(M, T) + ") | (" + toString(M, CTR) + "))" .
    eq parentsToInv(M, ([ ID, T, CTR, ACSB, 0 ], PARENTS)) = parentsToInv(M, [ ID, T, CTR, ACSB, 0 ]) + " \\/\n" + parentsToInv(M, PARENTS) .


    op toStringSub : Module DMCOutput TermSet -> String .
    eq toStringSub(M, noParents || CHILDREN, LEMMAS?) = errorMsg(0) .
    eq toStringSub(M, PARENTS || noChildren, mt) = "\033[1;32m  Subsumption satisfied.\033[0m\n" .
    eq toStringSub(M, PARENTS || noChildren, LEMMAS) = "\033[1;32m  Subsumption satisfied with the following proof obligations:\033[0m\n\n" + toStringLemmas(M, LEMMAS) .
    eq toStringSub(M, PARENTS || ([ ID, T, CTR, ACSB, ML, N ], CHILDREN), LEMMAS?) = "\033[1;31m  Constrained terms on the left that could not be subsumed:\033[0m\n" + toStringChildrenSub(M, ([ ID, T, CTR, ACSB, ML, N ], CHILDREN)) .

    op toStringInt : Module DMCOutput TermSet -> String .
    eq toStringInt(M, noParents || CHILDREN, LEMMAS?) = errorMsg(0) .
    eq toStringInt(M, PARENTS || noChildren, LEMMAS?) = "\033[1;32m  No intersection.\033[0m\n" .
    eq toStringInt(M, PARENTS || ([ ID, T, T', T'', CTR, LSB, RSB ], CHILDREN1), LEMMAS?) = "\033[1;31m  Intersection of constrained terms:\033[0m\n" + toStringChildrenInt(M, ([ ID, T, T', T'', CTR, LSB, RSB ], CHILDREN1)) .

    op toStringCtxs : Module VarAbsPair -> String .
    eq toStringCtxs(M, {ID, noChildren}) = "" .
    eq toStringCtxs(M, {ID, ([ ID', PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN)}) = 
        "\nTerm " + string(ID', 10) + ":\n  " + toString(M, T) +
        "\nConstraint " + string(ID', 10) + ":\n  " + toString(M, CTR) +
        "\n" + toStringCtxs(M, {ID, CHILDREN}) .
    eq toStringCtxs(M, {ID, ([ ID', T, CTR, ACSB, ML, N ], CHILDREN)}) = 
        "\nTerm " + string(ID', 10) + ":\n  " + toString(M, T) +
        "\nConstraint " + string(ID', 10) + ":\n  " + toString(M, CTR) +
        "\n" + toStringCtxs(M, {ID, CHILDREN}) .
endm

mod DM-CHECK-UI-SYNTAX is
    pr QID-LIST .

    sorts Token Bubble Command .

    op token : Qid -> Token [ special (id-hook Bubble (1 1) op-hook qidSymbol (<Qids> : ~> Qid)) ] .
    op bubble : QidList -> Bubble [ special (id-hook Bubble (1 -1 `( `)) op-hook qidListSymbol (__ : QidList QidList ~> QidList) op-hook qidSymbol (<Qids> : ~> Qid) id-hook Exclude (.)) ] .

    op q : -> Command .
    op quit : -> Command .
    op h`. : -> Command .
    op help`. : -> Command .
    op show`module`. : -> Command .
    op show`lemmas`. : -> Command .
    op show`last`. : -> Command .
    op show`obligations`. : -> Command .
    
    op set`module_. : Token -> Command .
    op add`lemma_. : Bubble -> Command .

    op check`invariant_. : Bubble -> Command .
    op check`ind-invariant_. : Bubble -> Command .
    op generate`ind-invariant_. : Bubble -> Command .
    op gen`ind-invariant_. : Bubble -> Command .
    op generate`next`level`. : -> Command .
    op gen`next`level`. : -> Command .
    op check_subsumed`by_. : Bubble Bubble -> Command .
    op intersect_with_. : Bubble Bubble -> Command .
    op empty_. : Token -> Command .
    op lemma_. : Token -> Command .
    op lemma_match_. : Token Token -> Command .
    op contained_. : Token -> Command .
    ---op recheck`. : -> Command . (DEPRECATED)
    op case`to_on_with_. : Token Token Bubble -> Command .
    op variable`abstraction_with_in_. : Bubble Token Token -> Command .
    op va_with_in_. : Bubble Token Token -> Command .
    op select`variable`abstraction_. : Token -> Command .
    op select`va_. : Token -> Command .
    op substitution`to_on_with_. : Token Token Bubble -> Command .
    op sb`to_on_with_. : Token Token Bubble -> Command .
    op variant`unify_=?_in_. : Bubble Bubble Token -> Command .
    op vunify_=?_in_. : Bubble Bubble Token -> Command .
    op narrowing_on_. : Token Bubble -> Command .
    op narrow_on_. : Token Bubble -> Command .
    op generalize_to_. : Bubble Bubble -> Command .
    op split_with_. : Token Bubble -> Command .

    op variant`unify`to_with_=?_. : Token Bubble Bubble -> Command . --- Temp
    op vunify`to_with_=?_. : Token Bubble Bubble -> Command . --- Temp
    op narrowing`to_on_. : Token Bubble -> Command . --- Temp
    op narrow`to_on_. : Token Bubble -> Command . --- Temp
    op variable`abstraction`to_on_with_. : Token Bubble Token -> Command . --- Temp
    op va`to_on_with_. : Token Bubble Token -> Command . --- Temp
endm

mod DM-CHECK-UI is
    pr DM-CHECK-STRING .
    pr DM-CHECK .
    pr STD-STREAM .
    pr FILE .
    
    sorts StringQid .
    
    op _|_ : String Qid -> StringQid [ ctor ] .
    
    op oid : -> Oid .
    op cid : -> Cid .

    op module:_ : [Module] -> Attribute [ ctor prec 20 gather (&) ] .
    op pos:_ : String -> Attribute [ ctor prec 20 gather (&) ] .
    op lemmasui:_ : TermSet -> Attribute [ ctor prec 20 gather (&) ] .
    op lastRes:_ : DMCOutput -> Attribute [ ctor prec 20 gather (&) ] .
    op lastCmd:_ : StringQid -> Attribute [ ctor prec 20 gather (&) ] .
    op tmpCmd:_ : String -> Attribute [ ctor prec 20 gather (&) ] .
    op vaSelect:_ : Bool -> Attribute [ ctor prec 20 gather (&) ] .
    op varAbs:_ : VarAbsPair -> Attribute [ ctor prec 20 gather (&) ] .

    op parse : Term -> Msg [ ctor ] .
    op checkInvariant : Module TermList -> Msg [ ctor ] .
    op genInvariant : Module TermList -> Msg [ ctor ] .
    op checkSubsumed : Module TermList TermList -> Msg [ ctor ] .
    op checkIntersect : Module TermList TermList -> Msg [ ctor ] .
    op noModule : -> [Module] [ ctor ] .
    
    var CID : Cid .
    var OID : Oid .
    var ATS : AttributeSet .
    
    var M : Module .
    vars Q Q' TYPE RL RL' LSTCMD : Qid .
    var H : Header .
    var IL : ImportList .
    var SS : SortSet .
    var SSDS : SubsortDeclSet .
    var OPDS : OpDeclSet .
    var MAS : MembAxSet .
    var EQS : EquationSet .
    var RLS : RuleSet .
    var STDS : StratDeclSet .
    var STDFS : StratDefSet .

    vars N N' ID ID' PID PID' ID1 ID2 PID1 PID2 MID : Nat .
    var NZ : NzNat .
    var STR : String .
    var M? : [Module] .
    var T? : [Term] .
    vars TL TL1 TL2 : TermList .
    vars TS TS' : TermSet .
    vars NTL NTL1 NTL2 TERMS INVARIANTS ARG ARG1 ARG2 ARG3 ARG4 : NeTermList .
    vars TERM TMODE TCONSTRAINT TOPTIONS TBOUNDS GAMMA DELTA LEMMA CTR CTR' INVARIANT INVARIANT1 INVARIANT2 IMPLICATION PARSED-TERM1 PARSED-TERM2 : Term .
    var PROBLEM? : TermList .
    vars NQL NQL1 NQL2 MODE OPTIONS BOUNDS MODULE CONSTRAINT LEMMAQID : NeQidList .
    vars MODE? OPTIONS? BOUNDS? MODULE? CONSTRAINT? QL QL1 QL2 : QidList .
    vars T T' T1 T2 : Term .
    var LEMMAS : TermSet .
    vars NAR NAR1 NAR2 : NarrowingApplyResult .
    vars ML ML' ML1 ML2 : MatcherList .
    vars CMD TMP POS : String .
    vars MATCH SB SB' SB1 SB2 ACSB ACSB' LSB RSB : Substitution .
    var PROOF : ProofState .
    var CO : Context .
    var TY : Type .
    var V : Variable .
    var NTS : NeTermSet .
    var VABSPAIR : VarAbsPair .
    vars PARSED-VAR PARSED-SUBTERM PARSED-EXP : [Term] .
    var PARSED-GENSET : [TermSet] .
    var PARENTS : ParentNodeList .
    vars CHILDREN CHILDREN1 CHILDREN2 CHILDREN3 CHILDREN4 : ChildNodeList .
    var OUTPUT : DMCOutput .
    
    op addImport : Module Qid -> Module .
    eq addImport(fmod H is IL sorts SS . SSDS OPDS MAS EQS endfm, Q') = fmod H is IL (protecting Q' .) sorts SS . SSDS OPDS MAS EQS endfm .
    eq addImport(mod H is IL sorts SS . SSDS OPDS MAS EQS RLS endm, Q') = mod H is IL (protecting Q' .) sorts SS . SSDS OPDS MAS EQS RLS endm .
    eq addImport(smod H is IL sorts SS . SSDS OPDS MAS EQS RLS STDS STDFS endsm, Q') = smod H is IL (protecting Q' .) sorts SS . SSDS OPDS MAS EQS RLS STDS STDFS endsm .
    eq addImport(fth Q is IL sorts SS . SSDS OPDS MAS EQS endfth, Q') = fth Q is IL (protecting Q' .) sorts SS . SSDS OPDS MAS EQS endfth .
    eq addImport(th Q is IL sorts SS . SSDS OPDS MAS EQS RLS endth, Q') = th Q is IL (protecting Q' .) sorts SS . SSDS OPDS MAS EQS RLS endth .
    eq addImport(sth H is IL sorts SS . SSDS OPDS MAS EQS RLS STDS STDFS endsth, Q') = sth H is IL (protecting Q' .) sorts SS . SSDS OPDS MAS EQS RLS STDS STDFS endsth .
    eq addImport(M, Q) = M [ owise ] .

    op init : -> Configuration .
    eq init = <> < oid : cid | module: noModule, lemmasui: mt, lastRes: noSolution, lastCmd: ("" | 'noType), tmpCmd: "", pos: "" > write(stdout, oid, "\n") .

    --- parse command
    op parseCommand : [Module] Oid String -> Msg .
    ceq parseCommand(noModule, OID, STR) = write(stdout, OID, errorMsg(1)) 
        if 'check_subsumed`by_.['bubble[ARG1],'bubble[ARG2]] := getTerm(metaParse(upModule('DM-CHECK-UI-SYNTAX, false), none, tokenize(STR), 'Command)) .
    ceq parseCommand(noModule, OID, STR) = write(stdout, OID, errorMsg(1)) 
        if 'check`ind-invariant_.['bubble[ARG1]] := getTerm(metaParse(upModule('DM-CHECK-UI-SYNTAX, false), none, tokenize(STR), 'Command)) .
    ceq parseCommand(noModule, OID, STR) = write(stdout, OID, errorMsg(1)) 
        if 'generate`ind-invariant_.['bubble[ARG1]] := getTerm(metaParse(upModule('DM-CHECK-UI-SYNTAX, false), none, tokenize(STR), 'Command)) .
    ceq parseCommand(noModule, OID, STR) = write(stdout, OID, errorMsg(1)) 
        if 'gen`ind-invariant_.['bubble[ARG1]] := getTerm(metaParse(upModule('DM-CHECK-UI-SYNTAX, false), none, tokenize(STR), 'Command)) .
    ceq parseCommand(noModule, OID, STR) = write(stdout, OID, errorMsg(1)) 
        if 'intersect_with_.['bubble[ARG1]] := getTerm(metaParse(upModule('DM-CHECK-UI-SYNTAX, false), none, tokenize(STR), 'Command)) .
    ceq parseCommand(noModule, OID, STR) = write(stdout, OID, errorMsg(1)) 
        if 'check_subsumed`by_.['bubble[ARG1],'bubble[ARG2]] := getTerm(metaParse(upModule('DM-CHECK-UI-SYNTAX, false), none, tokenize(STR), 'Command)) .
    ceq parseCommand(M, OID, STR) = parse('check_subsumed`by_.['bubble[ARG1],'bubble[ARG2]])
        if 'check_subsumed`by_.['bubble[ARG1],'bubble[ARG2]] := getTerm(metaParse(upModule('DM-CHECK-UI-SYNTAX, false), none, tokenize(STR), 'Command)) .
    eq parseCommand(M?, OID, STR) = parse(getTerm(metaParse(upModule('DM-CHECK-UI-SYNTAX, false), none, tokenize(STR), 'Command))) [ owise ] .
    
    --- quit
    eq < OID : CID | ATS > parse('q.Command) = (none).Configuration write(stdout, OID, "\n\033[1;37m  Bye.\033[0m\n\n") .
    eq < OID : CID | ATS > parse('quit.Command) = (none).Configuration write(stdout, OID, "\n\033[1;37m  Bye.\033[0m\n\n") .
    eq < OID : CID | ATS > parse(T?) = < OID : CID | ATS > write(stdout, OID, errorMsg(3)) [ owise ] .
    
    --- help
    eq < OID : CID | ATS > parse('h`..Command) = < OID : CID | ATS > write(stdout, OID, helpText) .
    eq < OID : CID | ATS > parse('help`..Command) = < OID : CID | ATS > write(stdout, OID, helpText) .

    --- Wrote / Got Line
    eq < OID : CID | ATS, vaSelect: true > wrote(OID, stdout) = < OID : CID | ATS, vaSelect: true > getLine(stdin, OID, "Select variable abstraction> ") .
    eq < OID : CID | ATS > wrote(OID, stdout) = < OID : CID | ATS > getLine(stdin, OID, "DM-Check> ") [ owise ] .
    
    eq < OID : CID | ATS, vaSelect: true, module: M?, tmpCmd: TMP > gotLine(OID, stdin, STR) = < OID : CID | ATS, vaSelect: true, module: M?, tmpCmd: STR > parseCommand(M?, OID, STR) .
    eq < OID : CID | ATS, module: M?, tmpCmd: TMP > gotLine(OID, stdin, STR) = < OID : CID | ATS, module: M?, tmpCmd: STR > parseCommand(M?, OID, STR) .
    
    eq getTerm(ambiguity({'true.Bool,'Bool}, {'true.NuITP-Bool,'NuITP-Bool})) = 'true.Bool .
    eq getTerm(ambiguity({T1, 'Disjunction}, {T2, 'Disjunction})) = T1 .

    --- set module MODNAME .
    eq < OID : CID | ATS, module: M?, tmpCmd: TMP, lastCmd: (CMD | TYPE), lastRes: OUTPUT, lemmasui: LEMMAS, pos: POS > parse('set`module_.['token[T]]) =
        if transformMod(upModule(downTerm(T, 'noModule.Qid), true)) :: Module
        then
            if countNarrowRls(upModule(downTerm(T, 'noModule.Qid), true)) == 0
            then
                < OID : CID | ATS, module: addImport(transformMod(upModule(downTerm(T, 'noModule.Qid), true)), 'NuITP-CLAUSE), tmpCmd: "", lastCmd: ("" | 'noType), lastRes: (noParents || noChildren), lemmasui: mt, pos: "" >
                write(stdout, OID, "\n\033[1;32m  Module " + string(downTerm(T, 'noModule.Qid)) + " is now active.\033[0m\n\n")
            else
                < OID : CID | ATS, module: addImport(transformMod(upModule(downTerm(T, 'noModule.Qid), true)), 'NuITP-CLAUSE), tmpCmd: "", lastCmd: ("" | 'noType), lastRes: (noParents || noChildren), lemmasui: mt, pos: "" >
                write(stdout, OID, "\n\033[1;32m  Module " + string(downTerm(T, 'noModule.Qid)) + " is now active.\033[0m\n" +
                                   errorMsg(26, countNarrowRls(upModule(downTerm(T, 'noModule.Qid), true))))
            fi
        else 
            < OID : CID | ATS, module: M?, tmpCmd: TMP, lastCmd: (CMD | TYPE), lastRes: OUTPUT, lemmasui: LEMMAS, pos: POS > write(stdout, oid, errorMsg(1))
        fi .

    --- recheck (DEPRECATED).
    --- eq < OID : CID | ATS, module: noModule > parse('recheck`..Command) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .
    --- eq < OID : CID | ATS, module: M, lastCmd: (CMD | 'invariant), tmpCmd: TMP > parse('recheck`..Command) = < OID : CID | ATS, module: M, lastCmd: (CMD | 'invariant), tmpCmd: CMD > parseCommand(M, OID, CMD) .
    --- eq < OID : CID | ATS, module: M, lastCmd: (CMD | 'generate), tmpCmd: TMP > parse('recheck`..Command) = < OID : CID | ATS, module: M, lastCmd: (CMD | 'generate), tmpCmd: CMD > parseCommand(M, OID, CMD) .
    --- eq < OID : CID | ATS, module: M, lastCmd: (CMD | 'subsumption), tmpCmd: TMP > parse('recheck`..Command) = < OID : CID | ATS, module: M, lastCmd: (CMD | 'subsumption), tmpCmd: CMD > parseCommand(M, OID, CMD) .
    --- eq < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > parse('recheck`..Command) = < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: CMD > parseCommand(M, OID, CMD) .
    --- eq < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > parse('recheck`..Command) = < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > write(stdout, oid, errorMsg(5)) .
    
    --- show module .
    eq < OID : CID | ATS, module: M > parse('show`module`..Command) = < OID : CID | ATS, module: M > write(stdout, OID, "\n\033[1;32m  Module " + string(getName(M)) + " is active.\033[0m\n\n") .
    eq < OID : CID | ATS, module: noModule > parse('show`module`..Command) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .

    --- show lemmas .
    eq < OID : CID | ATS, module: M, lemmasui: LEMMAS > parse('show`lemmas`..Command) = < OID : CID | ATS, module: M, lemmasui: LEMMAS > write(stdout, OID, "\n\033[1;32m  Current lemmas:\n\033[0m\n" + if (LEMMAS == mt) then "  No lemmas saved." else toStringLemmas(M, LEMMAS) fi + "\n\n") .
    eq < OID : CID | ATS, module: noModule > parse('show`lemmas`..Command) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .

    --- show proof obligations .
    eq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS > parse('show`obligations`..Command) = < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS > write(stdout, OID, "\n\033[1;32m  Current proof obligations:\n\033[0m\n" + 
        if ((LEMMAS == mt) and-then (POS == "")) 
        then "  No proof obligations pending.\n\n" 
        else toStringLemmas(M, LEMMAS) + "\n" + POS + "\n"
        fi) .
    eq < OID : CID | ATS, module: noModule > parse('show`obligations`..Command) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .

    --- show last .
    eq < OID : CID | ATS, module: M?, lastRes: OUTPUT, lastCmd: (CMD | 'noType) > parse('show`last`..Command) = < OID : CID | ATS, module: M?, lastRes: OUTPUT, lastCmd: (CMD | 'noType) > write(stdout, oid, errorMsg(5)) .
    eq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | 'invariant), pos: POS > parse('show`last`..Command) = < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | 'invariant), pos: POS > write(stdout, OID, "\n  " + toStringInv(M, OUTPUT, LEMMAS, POS) + "\n\n") .
    eq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | 'generate), pos: POS > parse('show`last`..Command) = < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | 'generate), pos: POS > write(stdout, OID, "\n  " + toStringGen(M, OUTPUT, LEMMAS, POS) + "\n\n") .
    eq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | 'subsumption) > parse('show`last`..Command) = < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | 'subsumption) > write(stdout, OID, "\n  " + toStringSub(M, OUTPUT, LEMMAS) + "\n\n") .
    eq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | 'intersect) > parse('show`last`..Command) = < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | 'intersect) > write(stdout, OID, "\n  " + toStringInt(M, OUTPUT, LEMMAS) + "\n\n") .

    op notFound : DMCOutput Nat -> Bool .
    eq notFound((PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)), ID) = false .
    eq notFound((PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)), ID) = false .
    eq notFound(OUTPUT, ID) = true [ owise ] .

    op notFound : ChildNodeList Nat -> Bool .
    eq notFound((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), ID) = false .
    eq notFound((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), ID) = false .
    eq notFound(CHILDREN, ID) = true [ owise ] .

    op notFound : DMCOutput QidList -> Bool .
    eq notFound(OUTPUT, (nil).QidList) = false .
    ceq notFound((PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)), (Q QL)) 
        = notFound((PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)), QL) 
    if ID == rat(string(Q),10) .
    ceq notFound((PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)), (Q QL)) 
        = notFound((PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)), QL)
    if ID == rat(string(Q),10) .
    eq notFound(OUTPUT, QL) = true [ owise ] .

    op allFound : ChildNodeList QidList -> Bool .
    eq allFound(CHILDREN, (nil).QidList) = true .
    ceq allFound((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), (Q QL)) 
        = allFound((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), QL) 
    if ID == rat(string(Q),10) .
    ceq allFound((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), (Q QL)) 
        = allFound((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), QL)
    if ID == rat(string(Q),10) .
    eq allFound(CHILDREN, QL) = false [ owise ] .
    
    op applySub : NarrowingApplyResult Substitution -> NarrowingApplyResult .
    eq applySub({ T1, TY, CO, Q, SB1, SB2, Q' }, V <- T) = { applySub(T1, V <- T), TY, CO, Q, applySub(SB1, V <- T), applySub(SB2, V <- T), Q' } .

    op applySub : MatcherList Substitution -> MatcherList .
    eq applySub((MID, MATCH, IMPLICATION, PROOF), SB) = (MID, applySub(MATCH, SB), applySub(IMPLICATION, SB), PROOF) .
    eq applySub((MID, MATCH, IMPLICATION, PROOF) ; ML, SB) = (MID, applySub(MATCH, SB), applySub(IMPLICATION, SB), PROOF) ; applySub(ML, SB) .
    eq applySub(ML, SB) = ML [ owise ] .
    
    op generateChildren : ChildNode Nat Variable TermSet -> ChildNodeList .
    eq generateChildren([ ID, PID, T', CTR, RL, SB, ACSB, ML, N' ], N, V, mt) = noChildren .
    eq generateChildren([ ID, PID, T', CTR, RL, SB, ACSB, ML, N' ], N, V, T) = [ N, PID, applySub(T', V <- T), applySub(CTR, V <- T), RL, applySub(SB, V <- T), applySub(ACSB, V <- T), applySub(ML, V <- T), N' ] .
    eq generateChildren([ ID, PID, T', CTR, RL, SB, ACSB, ML, N' ], N, V, T ;; NTS) = [ N, PID, applySub(T', V <- T), applySub(CTR, V <- T), RL, applySub(SB, V <- T), applySub(ACSB, V <- T), applySub(ML, V <- T), N' ] , generateChildren([ ID, PID, T', CTR, RL, SB, ACSB, ML, N' ], N + 1, V, NTS) .

    op getParents : ParentNodeList -> TermList .
    eq getParents(noParents) = empty .
    eq getParents(([ ID, T, CTR, ACSB, 0 ], PARENTS)) = ('_|_[T,CTR]) , getParents(PARENTS) .

    op getNextIndex : ChildNodeList Nat -> Nat .
    eq getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), N') = 
        if (ID >= N')
        then getNextIndex((CHILDREN1, CHILDREN2), ID) 
        else getNextIndex((CHILDREN1, CHILDREN2), N') 
        fi .
    eq getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), N') = 
        if (ID >= N')
        then getNextIndex((CHILDREN1, CHILDREN2), ID) 
        else getNextIndex((CHILDREN1, CHILDREN2), N') 
        fi .
    eq getNextIndex(CHILDREN, N) = s(N) [ owise ] .

    op getNextVar : ChildNodeList Nat -> Nat .
    eq getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), N')
        = if getNextVar(getVars(T) ;; getVars(CTR), 0) >= N'
          then getNextVar((CHILDREN1, CHILDREN2), getNextVar(getVars(T) ;; getVars(CTR), 0)) 
          else getNextVar((CHILDREN1, CHILDREN2), N') 
          fi .
    eq getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), N')
        = if getNextVar(getVars(T) ;; getVars(CTR), 0) >= N'
          then getNextVar((CHILDREN1, CHILDREN2), getNextVar(getVars(T) ;; getVars(CTR), 0)) 
          else getNextVar((CHILDREN1, CHILDREN2), N') 
          fi .
    eq getNextVar(CHILDREN, N) = s(N) [ owise ] .

    op getNextVar : TermSet Nat -> Nat .
    eq getNextVar(mt, N) = N .
    eq getNextVar((V ;; TS), N)
        = if rat(substr(string(getName(V)),1,length(string(getName(V)))),10) >= N
          then getNextVar(TS, rat(substr(string(getName(V)),1,length(string(getName(V)))),10))
          else getNextVar(TS, N) 
          fi . 

    op variableClash? : TermSet ChildNode -> Bool .
    eq variableClash?(TS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ]) = variableClash?'(getVars(TS), getVars(T)) .
    eq variableClash?(TS, [ ID, T, CTR, ACSB, ML, N ]) = variableClash?'(getVars(TS), getVars(T)) .

    op variableClash?' : TermSet TermSet -> Bool .
    eq variableClash?'(V ;; TS, V ;; TS') = true .
    eq variableClash?'(TS, TS') = false [ owise ] .

    op subTerm? : Module Term Term -> Bool .
    eq subTerm?(M, T, T')
        = if metaXmatch(addOps(M, freeze(getVars(T) ;; getVars(T'))), freeze(T), freeze(T'), nil, 0, unbounded, 0) :: MatchPair
          then true else false fi .

    --- case to CHILD on VARIABLE with GENERATOR-SET .
    eq < OID : CID | ATS, module: noModule > parse('case`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .
    eq < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > parse('case`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > write(stdout, oid, errorMsg(9)) .
    eq < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > parse('case`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > write(stdout, oid, errorMsg(5)) .
    ceq < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > parse('case`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > write(stdout, oid, errorMsg(6))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate or-else LSTCMD == 'subsumption)
        /\ ID := rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ notFound(OUTPUT, ID) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > parse('case`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = 
        if (PARSED-VAR :: Variable) and-then (PARSED-VAR in getVars(T))
        then 
            if (PARSED-GENSET :: TermSet) and-then (PARSED-GENSET =/= mt)
            then 
                if (variableClash?(PARSED-GENSET, [ ID, T, CTR, ACSB, ML, N ]))
                then < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(12))
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, case(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-VAR, PARSED-GENSET, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) > 
                    write(stdout, OID, "\n  " + toStringSub(M, (PARENTS || (CHILDREN1, CHILDREN2, case(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-VAR, PARSED-GENSET, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS)) + "\n\n")
                fi
            else < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(11))
            fi
        else < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(10))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-VAR := parseVariables(M, downTerm(ARG2, 'nil.QidList), getVars(T))
        /\ PARSED-GENSET := parseGenSet(setRls(M,none), getType(PARSED-VAR), downTerm(ARG3,'nil.QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('case`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = 
        if (PARSED-VAR :: Variable) and-then (PARSED-VAR in getVars(T))
        then 
            if (PARSED-GENSET :: TermSet) and-then (PARSED-GENSET =/= mt)
            then 
                if (variableClash?(PARSED-GENSET, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ]))
                then < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(12))
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, case(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-VAR, PARSED-GENSET, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) > 
                    write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || (CHILDREN1, CHILDREN2, case(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-VAR, PARSED-GENSET, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS), POS) + "\n\n")
                fi
            else < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(11))
            fi
        else < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(10))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-VAR := parseVariables(M, downTerm(ARG2, 'nil.QidList), getVars(T))
        /\ PARSED-GENSET := parseGenSet(setRls(M,none), getType(PARSED-VAR), downTerm(ARG3,'nil.QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('case`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = 
        if (PARSED-VAR :: Variable) and-then (PARSED-VAR in getVars(T))
        then 
            if (PARSED-GENSET :: TermSet) and-then (PARSED-GENSET =/= mt)
            then 
                if (variableClash?(PARSED-GENSET, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ]))
                then < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(12))
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, case(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-VAR, PARSED-GENSET, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) > 
                    write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || (CHILDREN1, CHILDREN2, case(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-VAR, PARSED-GENSET, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS), POS) + "\n\n")
                fi
            else < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(11))
            fi
        else < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(10))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-VAR := parseVariables(M, downTerm(ARG2, 'nil.QidList), getVars(T))
        /\ PARSED-GENSET := parseGenSet(setRls(M,none), getType(PARSED-VAR), downTerm(ARG3,'nil.QidList)) .

    --- variable abstraction to CHILD on SUBTERM with VARIABLE .
    eq < OID : CID | ATS, module: noModule > parse('variable`abstraction_with_in_.['bubble[ARG1],'token[ARG2],'token[ARG3]]) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .
    eq < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > parse('variable`abstraction_with_in_.['bubble[ARG1],'token[ARG2],'token[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > write(stdout, oid, errorMsg(9)) .
    eq < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > parse('variable`abstraction_with_in_.['bubble[ARG1],'token[ARG2],'token[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > write(stdout, oid, errorMsg(5)) .
    ceq < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > parse('variable`abstraction_with_in_.['bubble[ARG1],'token[ARG2],'token[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > write(stdout, oid, errorMsg(6))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate or-else LSTCMD == 'subsumption)
        /\ ID := rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ notFound(OUTPUT, ID) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > parse('variable`abstraction_with_in_.['bubble[ARG1],'token[ARG2],'token[ARG3]]) = 
        if (PARSED-VAR :: Variable)
        then
            if (PARSED-SUBTERM :: Term)
            then
                if (subTerm?(M, PARSED-SUBTERM, T) or subTerm?(extModule(M), PARSED-SUBTERM, CTR))
                then
                    if (variableClash?'(PARSED-VAR, getVars(T)))
                    then                       
                        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(14))    
                    else
                        if countChildren(getChildren(variableAbstraction(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) == 1
                        then
                            < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, getChildren(variableAbstraction(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS)), PARENTS, none, LEMMAS))) > 
                            write(stdout, OID, "\n  " + toStringSub(M, (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, getChildren(variableAbstraction(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS)), PARENTS, none, LEMMAS))), (LEMMAS)) + "\n\n")
                        else
                            < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)), vaSelect: true, varAbs: variableAbstraction(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS) > 
                            write(stdout, OID, "\n\033[1;36m  Possible variable abstractions:\033[0m\n  " + toStringCtxs(M, variableAbstraction(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS)) + "\n\n")
                        fi
                    fi 
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(19))
                fi
            else
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(13))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(10))
        fi
        if ID == rat(string(downTerm(ARG3, 'nil.QidList)),10)
        /\ PARSED-VAR := parseVariables(M, downTerm(ARG2, 'nil.QidList), getVars(T))
        /\ PARSED-SUBTERM := parseTerm(M, downTerm(ARG1, (nil).QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('variable`abstraction_with_in_.['bubble[ARG1],'token[ARG2],'token[ARG3]]) = 
        if (PARSED-VAR :: Variable)
        then
            if (PARSED-SUBTERM :: Term)
            then
                if (subTerm?(M, PARSED-SUBTERM, T) or subTerm?(extModule(M), PARSED-SUBTERM, CTR))
                then
                    if (variableClash?'(PARSED-VAR, getVars(T)))
                    then                       
                        < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(14))    
                    else
                        if countChildren(getChildren(variableAbstraction(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) == 1
                        then
                            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, getChildren(variableAbstraction(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS)), PARENTS, none, LEMMAS))) > 
                            write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, getChildren(variableAbstraction(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS)), PARENTS, none, LEMMAS))), (LEMMAS), POS) + "\n\n")
                        else
                            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)), vaSelect: true, varAbs: variableAbstraction(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS) > 
                            write(stdout, OID, "\n\033[1;36m  Possible variable abstractions:\033[0m\n  " + toStringCtxs(M, variableAbstraction(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS)) + "\n\n")
                        fi
                    fi 
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(19))
                fi
            else
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(13))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(10))
        fi
        if ID == rat(string(downTerm(ARG3, 'nil.QidList)),10)
        /\ PARSED-VAR := parseVariables(M, downTerm(ARG2, 'nil.QidList), getVars(T))
        /\ PARSED-SUBTERM := parseTerm(M, downTerm(ARG1, (nil).QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('variable`abstraction_with_in_.['bubble[ARG1],'token[ARG2],'token[ARG3]]) = 
        if (PARSED-VAR :: Variable)
        then
            if (PARSED-SUBTERM :: Term)
            then
                if (subTerm?(M, PARSED-SUBTERM, T) or subTerm?(extModule(M), PARSED-SUBTERM, CTR))
                then
                    if (variableClash?'(PARSED-VAR, getVars(T)))
                    then                       
                        < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(14))    
                    else
                        if countChildren(getChildren(variableAbstraction(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) == 1
                        then
                            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, getChildren(variableAbstraction(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS)), PARENTS, none, LEMMAS))) > 
                            write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, getChildren(variableAbstraction(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS)), PARENTS, none, LEMMAS))), (LEMMAS), POS) + "\n\n")
                        else
                            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)), vaSelect: true, varAbs: variableAbstraction(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS) > 
                            write(stdout, OID, "\n\033[1;36m  Possible variable abstractions:\033[0m\n  " + toStringCtxs(M, variableAbstraction(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, PARSED-VAR, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS)) + "\n\n")
                        fi
                    fi 
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(19))
                fi
            else
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(13))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(10))
        fi
        if ID == rat(string(downTerm(ARG3, 'nil.QidList)),10)
        /\ PARSED-VAR := parseVariables(M, downTerm(ARG2, 'nil.QidList), getVars(T))
        /\ PARSED-SUBTERM := parseTerm(M, downTerm(ARG1, (nil).QidList)) .
    eq < OID : CID | ATS > parse('va_with_in_.['bubble[ARG1],'token[ARG2],'token[ARG3]]) = < OID : CID | ATS > parse('variable`abstraction_with_in_.['bubble[ARG1],'token[ARG2],'token[ARG3]]) .
    eq < OID : CID | ATS > parse('variable`abstraction`to_on_with_.['token[ARG1],'bubble[ARG2],'token[ARG3]]) = < OID : CID | ATS > parse('variable`abstraction_with_in_.['bubble[ARG2],'token[ARG3],'token[ARG1]]) . --- Temp
    eq < OID : CID | ATS > parse('va`to_on_with_.['token[ARG1],'bubble[ARG2],'token[ARG3]]) = < OID : CID | ATS > parse('variable`abstraction_with_in_.['bubble[ARG2],'token[ARG3],'token[ARG1]]) . --- Temp

    --- Variable abstraction selection
    eq < OID : CID | ATS, vaSelect: true, varAbs: {ID, CHILDREN}, module: noModule > parse('select`variable`abstraction_.['token[ARG1]]) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .
    eq < OID : CID | ATS, vaSelect: true, varAbs: {ID, CHILDREN}, module: M, lastCmd: ("" | 'noType) > parse('select`variable`abstraction_.['token[ARG1]]) = < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > write(stdout, oid, errorMsg(5)) .
    ceq < OID : CID | ATS, vaSelect: true, varAbs: {ID, CHILDREN}, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > parse('select`variable`abstraction_.['token[ARG1]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > write(stdout, oid, errorMsg(6))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate or-else LSTCMD == 'subsumption)
        /\ ID' := rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ notFound(CHILDREN, ID') .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)), vaSelect: true, varAbs: {ID, (CHILDREN3, [ ID', T', CTR', ACSB', ML', N' ], CHILDREN4)} > parse('select`variable`abstraction_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, [ ID', T', CTR', ACSB', ML', N' ], PARENTS, none, LEMMAS))) > 
        write(stdout, OID, "\n  " + toStringSub(M, (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, [ ID', T', CTR', ACSB', ML', N' ], PARENTS, none, LEMMAS))), (LEMMAS)) + "\n\n")
        if ID' == rat(string(downTerm(ARG1, 'nil.QidList)),10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)), vaSelect: true, varAbs: {ID, (CHILDREN3, [ ID', PID', T', CTR', RL', SB', ACSB', ML', N' ], CHILDREN4)} > parse('select`variable`abstraction_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, [ ID', PID', T', CTR', RL', SB', ACSB', ML', N' ], PARENTS, none, LEMMAS))) > 
        write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, [ ID', PID', T', CTR', RL', SB', ACSB', ML', N' ], PARENTS, none, LEMMAS))), (LEMMAS), POS) + "\n\n")
        if ID' == rat(string(downTerm(ARG1, 'nil.QidList)),10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)), vaSelect: true, varAbs: {ID, (CHILDREN3, [ ID', PID', T', CTR', RL', SB', ACSB', ML', N' ], CHILDREN4)} > parse('select`variable`abstraction_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, [ ID', PID', T', CTR', RL', SB', ACSB', ML', N' ], PARENTS, none, LEMMAS))) > 
        write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || (CHILDREN1, CHILDREN2, applyVarAbs(M, [ ID', PID', T', CTR', RL', SB', ACSB', ML', N' ], PARENTS, none, LEMMAS))), (LEMMAS), POS) + "\n\n")
        if ID' == rat(string(downTerm(ARG1, 'nil.QidList)),10) .
    eq < OID : CID | ATS > parse('select`va_.['token[ARG1]]) = < OID : CID | ATS > parse('select`variable`abstraction_.['token[ARG1]]) .

    --- substitution to CHILD on VARIABLE with TERM .
    eq < OID : CID | ATS, module: noModule > parse('substitution`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .
    eq < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > parse('substitution`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > write(stdout, oid, errorMsg(9)) .
    eq < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > parse('substitution`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > write(stdout, oid, errorMsg(5)) .
    ceq < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > parse('substitution`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > write(stdout, oid, errorMsg(6))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate or-else LSTCMD == 'subsumption)
        /\ ID := rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ notFound(OUTPUT, ID) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > parse('substitution`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) =
        if (PARSED-VAR :: Variable) and-then (PARSED-VAR in getVars(T))
        then
            if (subTerm?(M, PARSED-VAR, T) or subTerm?(extModule(M), PARSED-VAR, CTR))
            then
                if (PARSED-SUBTERM :: Term)
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, subsCommand(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-VAR, PARSED-SUBTERM, getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS), CHILDREN2)) > 
                    write(stdout, OID, "\n  " + toStringSub(M, (PARENTS || (CHILDREN1, subsCommand(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-VAR, PARSED-SUBTERM, getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS), CHILDREN2)), (LEMMAS)) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(13))
                fi
            else
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(20))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(10))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-VAR := parseVariables(M, downTerm(ARG2, 'nil.QidList), mt) 
        /\ PARSED-SUBTERM := parseTerm(M, downTerm(ARG3, (nil).QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('substitution`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = 
        if (PARSED-VAR :: Variable)
        then
            if (subTerm?(M, PARSED-VAR, T) or subTerm?(extModule(M), PARSED-VAR, CTR))
            then
                if (PARSED-SUBTERM :: Term)
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, subsCommand(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-VAR, PARSED-SUBTERM, getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS), CHILDREN2)) > 
                    write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || (CHILDREN1, subsCommand(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-VAR, PARSED-SUBTERM, getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS), CHILDREN2)), (LEMMAS), POS) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(13))
                fi
            else
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(20))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(10))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-VAR := parseVariables(M, downTerm(ARG2, 'nil.QidList), mt) 
        /\ PARSED-SUBTERM := parseTerm(M, downTerm(ARG3, (nil).QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('substitution`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = 
        if (PARSED-VAR :: Variable)
        then
            if (subTerm?(M, PARSED-VAR, T) or subTerm?(extModule(M), PARSED-VAR, CTR))
            then
                if (PARSED-SUBTERM :: Term)
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, subsCommand(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-VAR, PARSED-SUBTERM, getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS), CHILDREN2)) > 
                    write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || (CHILDREN1, subsCommand(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-VAR, PARSED-SUBTERM, getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS), CHILDREN2)), (LEMMAS), POS) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(13))
                fi
            else
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(20))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(10))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-VAR := parseVariables(M, downTerm(ARG2, 'nil.QidList), mt) 
        /\ PARSED-SUBTERM := parseTerm(M, downTerm(ARG3, (nil).QidList)) .
    eq < OID : CID | ATS > parse('sb`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) = < OID : CID | ATS > parse('substitution`to_on_with_.['token[ARG1],'token[ARG2],'bubble[ARG3]]) .

    --- variant unify to CHILD with TERM1 =? TERM2 .
    eq < OID : CID | ATS, module: noModule > parse('variant`unify_=?_in_.['bubble[ARG1],'bubble[ARG2],'token[ARG3]]) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .
    eq < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > parse('variant`unify_=?_in_.['bubble[ARG1],'bubble[ARG2],'token[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > write(stdout, oid, errorMsg(9)) .
    eq < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > parse('variant`unify_=?_in_.['bubble[ARG1],'bubble[ARG2],'token[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > write(stdout, oid, errorMsg(5)) .
    ceq < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > parse('variant`unify_=?_in_.['bubble[ARG1],'bubble[ARG2],'token[ARG3]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > write(stdout, oid, errorMsg(6))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate or-else LSTCMD == 'subsumption)
        /\ ID := rat(string(downTerm(ARG3, 'nil.QidList)),10)
        /\ notFound(OUTPUT, ID) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > parse('variant`unify_=?_in_.['bubble[ARG1],'bubble[ARG2],'token[ARG3]]) = 
        if (PARSED-TERM1 :: Term)
        then
            if (PARSED-TERM2 :: Term)
            then
                if (subTerm?(M, PARSED-TERM1, T) or subTerm?(extModule(M), PARSED-TERM1, CTR) or
                    subTerm?(M, PARSED-TERM2, T) or subTerm?(extModule(M), PARSED-TERM2, CTR))
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, vunify(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-TERM1, PARSED-TERM2, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) > 
                    write(stdout, OID, "\n  " + toStringSub(M, (PARENTS || (CHILDREN1, CHILDREN2, vunify(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-TERM1, PARSED-TERM2, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS)) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(19))
                fi
            else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(17))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(16))
        fi
        if ID == rat(string(downTerm(ARG3, 'nil.QidList)),10)
        /\ PARSED-TERM1 := parseTerm(M, downTerm(ARG1, (nil).QidList)) 
        /\ PARSED-TERM2 := parseTerm(M, downTerm(ARG2, (nil).QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('variant`unify_=?_in_.['bubble[ARG1],'bubble[ARG2],'token[ARG3]]) = 
        if (PARSED-TERM1 :: Term)
        then
            if (PARSED-TERM2 :: Term)
            then
                if (subTerm?(M, PARSED-TERM1, T) or subTerm?(extModule(M), PARSED-TERM1, CTR) or
                    subTerm?(M, PARSED-TERM2, T) or subTerm?(extModule(M), PARSED-TERM2, CTR))
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, vunify(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-TERM1, PARSED-TERM2, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) > 
                    write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || (CHILDREN1, CHILDREN2, vunify(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-TERM1, PARSED-TERM2, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS), POS) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(19))
                fi
            else
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(17))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(16))
        fi
        if ID == rat(string(downTerm(ARG3, 'nil.QidList)),10)
        /\ PARSED-TERM1 := parseTerm(M, downTerm(ARG1, (nil).QidList)) 
        /\ PARSED-TERM2 := parseTerm(M, downTerm(ARG2, (nil).QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('variant`unify_=?_in_.['bubble[ARG1],'bubble[ARG2],'token[ARG3]]) = 
        if (PARSED-TERM1 :: Term)
        then
            if (PARSED-TERM2 :: Term)
            then
                if (subTerm?(M, PARSED-TERM1, T) or subTerm?(extModule(M), PARSED-TERM1, CTR) or
                    subTerm?(M, PARSED-TERM2, T) or subTerm?(extModule(M), PARSED-TERM2, CTR))
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, vunify(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-TERM1, PARSED-TERM2, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) > 
                    write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || (CHILDREN1, CHILDREN2, vunify(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-TERM1, PARSED-TERM2, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS), POS) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(19))
                fi
            else
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(17))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(16))
        fi
        if ID == rat(string(downTerm(ARG3, 'nil.QidList)),10)
        /\ PARSED-TERM1 := parseTerm(M, downTerm(ARG1, (nil).QidList)) 
        /\ PARSED-TERM2 := parseTerm(M, downTerm(ARG2, (nil).QidList)) .
    eq < OID : CID | ATS > parse('vunify_=?_in_.['bubble[ARG1],'bubble[ARG2],'token[ARG3]]) = < OID : CID | ATS > parse('variant`unify_=?_in_.['bubble[ARG1],'bubble[ARG2],'token[ARG3]]) .
    eq < OID : CID | ATS > parse('vunify`to_with_=?_.['token[ARG3],'bubble[ARG1],'bubble[ARG2]]) = < OID : CID | ATS > parse('variant`unify_=?_in_.['bubble[ARG1],'bubble[ARG2],'token[ARG3]]) . --- Temp
    eq < OID : CID | ATS > parse('variant`unify`to_with_=?_.['token[ARG3],'bubble[ARG1],'bubble[ARG2]]) = < OID : CID | ATS > parse('variant`unify_=?_in_.['bubble[ARG1],'bubble[ARG2],'token[ARG3]]) . --- Temp
    
    --- narrowing to CHILD on SUBTERM .
    eq < OID : CID | ATS, module: noModule > parse('narrowing_on_.['token[ARG1],'bubble[ARG2]]) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .
    eq < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > parse('narrowing_on_.['token[ARG1],'bubble[ARG2]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > write(stdout, oid, errorMsg(9)) .
    eq < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > parse('narrowing_on_.['token[ARG1],'bubble[ARG2]]) = < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > write(stdout, oid, errorMsg(5)) .
    ceq < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > parse('narrowing_on_.['token[ARG1],'bubble[ARG2]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > write(stdout, oid, errorMsg(6))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate or-else LSTCMD == 'subsumption)
        /\ ID := rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ notFound(OUTPUT, ID) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > parse('narrowing_on_.['token[ARG1],'bubble[ARG2]]) = 
        if (PARSED-SUBTERM :: Term)
        then
            if (subTerm?(M, PARSED-SUBTERM, T) or subTerm?(extModule(M), PARSED-SUBTERM, CTR))
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, narrow(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-SUBTERM, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) > 
                    write(stdout, OID, "\n  " + toStringSub(M, (PARENTS || (CHILDREN1, CHILDREN2, narrow(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-SUBTERM, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS)) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(19))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(13))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-SUBTERM := parseTerm(M, downTerm(ARG2, (nil).QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('narrowing_on_.['token[ARG1],'bubble[ARG2]]) = 
        if (PARSED-SUBTERM :: Term)
        then
            if (subTerm?(M, PARSED-SUBTERM, T) or subTerm?(extModule(M), PARSED-SUBTERM, CTR))
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, narrow(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) > 
                    write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || (CHILDREN1, CHILDREN2, narrow(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS), POS) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(19))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(13))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-SUBTERM := parseTerm(M, downTerm(ARG2, (nil).QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('narrowing_on_.['token[ARG1],'bubble[ARG2]]) = 
        if (PARSED-SUBTERM :: Term)
        then
            if (subTerm?(M, PARSED-SUBTERM, T) or subTerm?(extModule(M), PARSED-SUBTERM, CTR))
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, narrow(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) > 
                    write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || (CHILDREN1, CHILDREN2, narrow(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-SUBTERM, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS), POS) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(19))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(13))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-SUBTERM := parseTerm(M, downTerm(ARG2, (nil).QidList)) .
    eq < OID : CID | ATS > parse('narrow_on_.['token[ARG1],'bubble[ARG2]]) = < OID : CID | ATS > parse('narrowing_on_.['token[ARG1],'bubble[ARG2]]) .
    eq < OID : CID | ATS > parse('narrowing`to_on_.['token[ARG1],'bubble[ARG2]]) = < OID : CID | ATS > parse('narrowing_on_.['token[ARG1],'bubble[ARG2]]) . --- Temp
    eq < OID : CID | ATS > parse('narrow`to_on_.['token[ARG1],'bubble[ARG2]]) = < OID : CID | ATS > parse('narrowing_on_.['token[ARG1],'bubble[ARG2]]) . --- Temp

    --- Generate next level
    eq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || CHILDREN) > parse('generate`next`level`..Command) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: genInvariant(M, nodesToInv(PARENTS || noChildren), genNextLevel(M, (PARENTS || CHILDREN), LEMMAS), LEMMAS) >
        write(stdout, OID, "\n  " + toStringGen(M, genInvariant(M, nodesToInv(PARENTS || noChildren), genNextLevel(M, (PARENTS || CHILDREN), LEMMAS), LEMMAS), (LEMMAS), POS) + "\n\n") .
    eq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || CHILDREN) > parse('gen`next`level`..Command) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || CHILDREN) > parse('generate`next`level`..Command) .

    --- Generalize using PATTERN
    eq < OID : CID | ATS, module: noModule > parse('generalize_to_.['bubble[ARG1],'bubble[ARG2]]) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .
    ceq < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), tmpCmd: TMP > parse('generalize_to_.['bubble[ARG1],'bubble[ARG2]]) 
        = < OID : CID | ATS, module: noModule, lastCmd: (CMD | LSTCMD), tmpCmd: TMP > write(stdout, oid, errorMsg(23)) 
        if LSTCMD == 'subsumption or-else LSTCMD == 'intersect .
    eq < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > parse('generalize_to_.['bubble[ARG1],'bubble[ARG2]]) = < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > write(stdout, oid, errorMsg(5)) .
    ceq < OID : CID | ATS, module: M, lastCmd: (CMD | 'generate), lastRes: OUTPUT > parse('generalize_to_.['bubble[ARG1],'bubble[ARG2]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | 'generate), lastRes: OUTPUT > write(stdout, oid, errorMsg(6))
        if notFound(OUTPUT, downTerm(ARG1, 'nil.QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || CHILDREN) > parse('generalize_to_.['bubble[ARG1],'bubble[ARG2]]) = 
        if (parseInvariant(M, downTerm(ARG2, 'nil.QidList)) :: TermList)
        then
            if getVars(parseInvariant(M, downTerm(ARG2, 'nil.QidList))) in getVars(CHILDREN)
            then
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || CHILDREN) > write(stdout, oid, errorMsg(22))
            else
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || generalize(M, PARENTS, CHILDREN, parseInvariant(M, downTerm(ARG2, 'nil.QidList)), getNextVar(CHILDREN, 0), none, LEMMAS, downTerm(ARG1, 'nil.QidList))) > 
                write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || generalize(M, PARENTS, CHILDREN, parseInvariant(M, downTerm(ARG2, 'nil.QidList)), getNextVar(CHILDREN, 0), none, LEMMAS, downTerm(ARG1, 'nil.QidList))), (LEMMAS), POS) + "\n\n")
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || CHILDREN) > write(stdout, oid, errorMsg(21))
        fi 
        if allFound(CHILDREN, downTerm(ARG1, 'nil.QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || CHILDREN) > parse('generalize_to_.['bubble[ARG1],'bubble[ARG2]]) = 
        if (parseInvariant(M, downTerm(ARG2, 'nil.QidList)) :: TermList)
        then
            if getVars(parseInvariant(M, downTerm(ARG2, 'nil.QidList))) in getVars(CHILDREN)
            then
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || CHILDREN) > write(stdout, oid, errorMsg(22))
            else
                < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || generalize(M, PARENTS, CHILDREN, parseInvariant(M, downTerm(ARG2, 'nil.QidList)), getNextVar(CHILDREN, 0), none, LEMMAS, downTerm(ARG1, 'nil.QidList))) > 
                write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || generalize(M, PARENTS, CHILDREN, parseInvariant(M, downTerm(ARG2, 'nil.QidList)), getNextVar(CHILDREN, 0), none, LEMMAS, downTerm(ARG1, 'nil.QidList))), (LEMMAS), POS) + "\n\n")
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || CHILDREN) > write(stdout, oid, errorMsg(21))
        fi 
        if allFound(CHILDREN, downTerm(ARG1, 'nil.QidList)) .

    --- Split using PATTERN
    eq < OID : CID | ATS, module: noModule > parse('split_with_.['token[ARG1],'bubble[ARG2]]) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .
    eq < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > parse('split_with_.['token[ARG1],'bubble[ARG2]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | 'intersect), tmpCmd: TMP > write(stdout, oid, errorMsg(9)) .
    eq < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > parse('split_with_.['token[ARG1],'bubble[ARG2]]) = < OID : CID | ATS, module: M, lastCmd: ("" | 'noType) > write(stdout, oid, errorMsg(5)) .
    ceq < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > parse('split_with_.['token[ARG1],'bubble[ARG2]]) = < OID : CID | ATS, module: M, lastCmd: (CMD | LSTCMD), lastRes: OUTPUT > write(stdout, oid, errorMsg(6))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate or-else LSTCMD == 'subsumption)
        /\ ID := rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ notFound(OUTPUT, ID) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > parse('split_with_.['token[ARG1],'bubble[ARG2]]) = 
        if (leastSort(M, PARSED-EXP) == 'Bool)
        then
            if (getVars(PARSED-EXP) in getVars(T) ;; getVars(CTR))
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, split(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-EXP, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) >
                    write(stdout, OID, "\n  " + toStringSub(M, (PARENTS || (CHILDREN1, CHILDREN2, split(M, PARENTS, [ ID, T, CTR, ACSB, ML, N ], PARSED-EXP, getNextIndex((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS)) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(25))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | 'subsumption), lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(24))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-EXP := parseTerm(M, downTerm(ARG2, (nil).QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('split_with_.['token[ARG1],'bubble[ARG2]]) = 
        if (leastSort(M, PARSED-EXP) == 'Bool)
        then
            if (getVars(PARSED-EXP) in getVars(T) ;; getVars(CTR))
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, split(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-EXP, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) >
                    write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || (CHILDREN1, CHILDREN2, split(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-EXP, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS), POS) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(25))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'invariant), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(24))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-EXP := parseTerm(M, downTerm(ARG2, (nil).QidList)) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > parse('split_with_.['token[ARG1],'bubble[ARG2]]) = 
        if (leastSort(M, PARSED-EXP) == 'Bool)
        then
            if (getVars(PARSED-EXP) in getVars(T) ;; getVars(CTR))
                then
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, CHILDREN2, split(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-EXP, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))) >
                    write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || (CHILDREN1, CHILDREN2, split(M, PARENTS, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], PARSED-EXP, getNextIndex((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), getNextVar((CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2), 0), none, LEMMAS))), (LEMMAS), POS) + "\n\n")
                else
                    < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(25))
            fi
        else
            < OID : CID | ATS, module: M, lemmasui: LEMMAS, pos: POS, lastCmd: (CMD | 'generate), lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)) > write(stdout, oid, errorMsg(24))
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ PARSED-EXP := parseTerm(M, downTerm(ARG2, (nil).QidList)) .

    --- empty CHILD .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)), lastCmd: (CMD | 'invariant), pos: POS > parse('empty_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: (LEMMAS ;; ('_->_[CTR,'false.NuITP-Bool])), lastRes: (PARENTS || (CHILDREN1,CHILDREN2)), lastCmd: (CMD | 'invariant), pos: POS > write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || (CHILDREN1,CHILDREN2)), (LEMMAS ;; ('_->_[CTR,'false.NuITP-Bool])), POS) + "\n\n")
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)), lastCmd: (CMD | 'generate), pos: POS > parse('empty_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: (LEMMAS ;; ('_->_[CTR,'false.NuITP-Bool])), lastRes: (PARENTS || (CHILDREN1,CHILDREN2)), lastCmd: (CMD | 'generate), pos: POS > write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || (CHILDREN1,CHILDREN2)), (LEMMAS ;; ('_->_[CTR,'false.NuITP-Bool])), POS) + "\n\n")
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, ML, N ], CHILDREN2)), lastCmd: (CMD | 'subsumption) > parse('empty_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: (LEMMAS ;; ('_->_[CTR,'false.NuITP-Bool])), lastRes: (PARENTS || (CHILDREN1,CHILDREN2)), lastCmd: (CMD | 'subsumption) > write(stdout, OID, "\n  " + toStringSub(M, (PARENTS || (CHILDREN1,CHILDREN2)), (LEMMAS ;; ('_->_[CTR,'false.NuITP-Bool]))) + "\n\n")
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | LSTCMD) > parse('empty_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | LSTCMD) > write(stdout, oid, errorMsg(6))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate or-else LSTCMD == 'subsumption)
        /\ ID := rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ notFound(OUTPUT, ID) .

    op getLemma : MatcherList Nat -> TermSet .
    eq getLemma((MID, MATCH, IMPLICATION, PROOF) ; ML, s(0)) = IMPLICATION .
    eq getLemma((MID, MATCH, IMPLICATION, PROOF) ; ML, s(NZ)) = getLemma(ML, NZ) .
    eq getLemma(ML, N) = mt [ owise ] .

    --- lemma CHILD .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, noMatch, N ], CHILDREN2)), lastCmd: (CMD | LSTCMD), pos: POS > parse('lemma_.['token[ARG1]]) = < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, noMatch, N ], CHILDREN2)), lastCmd: (CMD | LSTCMD), pos: POS > write(stdout, oid, errorMsg(7))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate or-else LSTCMD == 'subsumption)
        /\ ID == rat(string(downTerm(ARG1, 'nil.QidList)), 10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, (MID, MATCH, IMPLICATION, PROOF) ; ML, N ], CHILDREN2)), lastCmd: (CMD | 'invariant), pos: POS > parse('lemma_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: (LEMMAS ;; IMPLICATION), lastRes: (PARENTS || (CHILDREN1,CHILDREN2)), lastCmd: (CMD | 'invariant), pos: POS > write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || (CHILDREN1,CHILDREN2)), (LEMMAS ;; IMPLICATION), POS) + "\n\n")
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)), 10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, (MID, MATCH, IMPLICATION, PROOF) ; ML, N ], CHILDREN2)), lastCmd: (CMD | 'generate), pos: POS > parse('lemma_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: (LEMMAS ;; IMPLICATION), lastRes: (PARENTS || (CHILDREN1,CHILDREN2)), lastCmd: (CMD | 'generate), pos: POS > write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || (CHILDREN1,CHILDREN2)), (LEMMAS ;; IMPLICATION), POS) + "\n\n")
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)), 10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, T, CTR, ACSB, (MID, MATCH, IMPLICATION, PROOF) ; ML, N ], CHILDREN2)), lastCmd: (CMD | 'subsumption) > parse('lemma_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: (LEMMAS ;; IMPLICATION), lastRes: (PARENTS || (CHILDREN1,CHILDREN2)), lastCmd: (CMD | 'subsumption) > write(stdout, OID, "\n  " + toStringSub(M, (PARENTS || (CHILDREN1,CHILDREN2)), (LEMMAS ;; IMPLICATION)) + "\n\n")
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)), 10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | LSTCMD) > parse('lemma_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | LSTCMD) > write(stdout, oid, errorMsg(6))
        if ID := rat(string(downTerm(ARG1, 'nil.QidList)), 10)
        /\ notFound(OUTPUT, ID) .

    --- lemma CHILD match MATCHER .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, noMatch, N ], CHILDREN2)), lastCmd: (CMD | LSTCMD), pos: POS > parse('lemma_match_.['token[ARG1],'token[ARG2]]) = < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, noMatch, N ], CHILDREN2)), lastCmd: (CMD | LSTCMD), pos: POS > write(stdout, oid, errorMsg(7))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate)
        /\ ID == rat(string(downTerm(ARG1, 'nil.QidList)),10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, (MID, MATCH, IMPLICATION, PROOF) ; ML, N ], CHILDREN2)), lastCmd: (CMD | LSTCMD), pos: POS > parse('lemma_match_.['token[ARG1],'token[ARG2]]) = 
        if (getLemma((MID, MATCH, IMPLICATION, PROOF) ; ML, NZ) == mt)
        then < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, (MID, MATCH, IMPLICATION, PROOF) ; ML, N ], CHILDREN2)), lastCmd: (CMD | 'invariant), pos: POS > write(stdout, oid, errorMsg(8))
        else < OID : CID | ATS, module: M, lemmasui: (LEMMAS ;; getLemma((MID, MATCH, IMPLICATION, PROOF) ; ML, NZ)), lastRes: (PARENTS || (CHILDREN1,CHILDREN2)), lastCmd: (CMD | 'invariant), pos: POS > write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || (CHILDREN1,CHILDREN2)), (LEMMAS ;; getLemma((MID, MATCH, IMPLICATION, PROOF) ; ML, NZ)), POS) + "\n\n")
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)), 10)
        /\ NZ := rat(string(downTerm(ARG2, 'nil.QidList)), 10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, (MID, MATCH, IMPLICATION, PROOF) ; ML, N ], CHILDREN2)), lastCmd: (CMD | LSTCMD), pos: POS > parse('lemma_match_.['token[ARG1],'token[ARG2]]) = 
        if (getLemma((MID, MATCH, IMPLICATION, PROOF) ; ML, NZ) == mt)
        then < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, (MID, MATCH, IMPLICATION, PROOF) ; ML, N ], CHILDREN2)), lastCmd: (CMD | 'generate), pos: POS > write(stdout, oid, errorMsg(8))
        else < OID : CID | ATS, module: M, lemmasui: (LEMMAS ;; getLemma((MID, MATCH, IMPLICATION, PROOF) ; ML, NZ)), lastRes: (PARENTS || (CHILDREN1,CHILDREN2)), lastCmd: (CMD | 'generate), pos: POS > write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || (CHILDREN1,CHILDREN2)), (LEMMAS ;; getLemma((MID, MATCH, IMPLICATION, PROOF) ; ML, NZ)), POS) + "\n\n")
        fi
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)), 10)
        /\ NZ := rat(string(downTerm(ARG2, 'nil.QidList)), 10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | LSTCMD) > parse('lemma_match_.['token[ARG1],'token[ARG2]]) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | LSTCMD) > write(stdout, oid, errorMsg(6))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate)
        /\ ID := rat(string(downTerm(ARG1, 'nil.QidList)), 10)
        /\ notFound(OUTPUT, ID) .

    --- Build PO
    op buildPO : Module Term Term ParentNodeList -> String .
    eq buildPO(M, T1, T2, noParents) = "" .
    eq buildPO(M, T1, T2, PARENTS) = "  check (" + toString(M, T1) + " | " + toString(M, T2) + ") contained in " + buildPO'(M, PARENTS) + " .\n" [ owise ] .

    op buildPO' : Module ParentNodeList -> String .
    eq buildPO'(M, noParents) = "" .
    eq buildPO'(M, [ ID, T, CTR, ACSB, 0 ]) = "(" + toString(M, T) + " | " + toString(M, CTR) + ")" .
    eq buildPO'(M, ([ ID, T, CTR, ACSB, 0 ], PARENTS)) = "(" + toString(M, T) + " | " + toString(M, CTR) + ") \\/ " + buildPO'(M, PARENTS) .

    --- contained CHILD .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)), lastCmd: (CMD | 'invariant), pos: POS > parse('contained_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, CHILDREN2)), lastCmd: (CMD | 'invariant), pos: (POS + (if POS == "" then "" else "\n" fi) + buildPO(M, T, CTR, PARENTS)) > write(stdout, OID, "\n  " + toStringInv(M, (PARENTS || (CHILDREN1, CHILDREN2)), LEMMAS, (POS + (if POS == "" then "" else "\n" fi) + buildPO(M, T, CTR, PARENTS))) + "\n\n")
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, [ ID, PID, T, CTR, RL, SB, ACSB, ML, N ], CHILDREN2)), lastCmd: (CMD | 'generate), pos: POS > parse('contained_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: (PARENTS || (CHILDREN1, CHILDREN2)), lastCmd: (CMD | 'generate), pos: (POS + (if POS == "" then "" else "\n" fi) + buildPO(M, T, CTR, PARENTS)) > write(stdout, OID, "\n  " + toStringGen(M, (PARENTS || (CHILDREN1, CHILDREN2)), LEMMAS, (POS + (if POS == "" then "" else "\n" fi) + buildPO(M, T, CTR, PARENTS))) + "\n\n")
        if ID == rat(string(downTerm(ARG1, 'nil.QidList)),10) .
    ceq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | LSTCMD) > parse('contained_.['token[ARG1]]) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | LSTCMD) > write(stdout, oid, errorMsg(6))
        if (LSTCMD == 'invariant or-else LSTCMD == 'generate)
        /\ ID := rat(string(downTerm(ARG1, 'nil.QidList)),10)
        /\ notFound(OUTPUT, ID) .

    --- check INVARIANT .
    eq < OID : CID | ATS, module: M > parse('check`ind-invariant_.['bubble[ARG]]) = 
        if (parseInvariant(M, downTerm(ARG, 'nil.QidList)) :: TermList)
        then < OID : CID | ATS, module: M > checkInvariant(M, parseInvariant(M, downTerm(ARG, 'nil.QidList)))
        else < OID : CID | ATS, module: M > write(stdout, oid, errorMsg(2))
        fi .
    eq < OID : CID | ATS, module: M > parse('check`invariant_.['bubble[ARG]]) = < OID : CID | ATS, module: M > parse('check`ind-invariant_.['bubble[ARG]]) .

    ceq [do-check-inv] : < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | Q), tmpCmd: TMP, pos: POS > checkInvariant(M, ARG) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: checkInvariant(M, ARG, none, LEMMAS, 1), lastCmd: (TMP | 'invariant), tmpCmd: TMP, pos: POS >
        if toStringInv(M, checkInvariant(M, ARG, none, LEMMAS, 1), LEMMAS, POS) :: String
        then write(stdout, OID, "\n  " + toStringInv(M, checkInvariant(M, ARG, none, LEMMAS, 1), LEMMAS, POS) + "\n\n")
        else write(stdout, OID, errorMsg(0))
        fi 
    if Q == 'invariant or-else Q == 'noType .

    eq [do-check-inv] : < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | Q), tmpCmd: TMP, pos: POS > checkInvariant(M, ARG) = 
        < OID : CID | ATS, module: M, lemmasui: mt, lastRes: checkInvariant(M, ARG, none, mt, 1), lastCmd: (TMP | 'invariant), tmpCmd: TMP, pos: "" >
        if toStringInv(M, checkInvariant(M, ARG, none, mt, 1), mt, "") :: String
        then write(stdout, OID, "\n  " + toStringInv(M, checkInvariant(M, ARG, none, mt, 1), mt, "") + "\n\n")
        else write(stdout, OID, errorMsg(0))
        fi [owise] .

    --- generate INVARIANT .
    eq < OID : CID | ATS, module: M > parse('generate`ind-invariant_.['bubble[ARG]]) = 
        if (parseInvariant(M, downTerm(ARG, 'nil.QidList)) :: TermList)
        then < OID : CID | ATS, module: M > genInvariant(M, parseInvariant(M, downTerm(ARG, 'nil.QidList)))
        else < OID : CID | ATS, module: M > write(stdout, oid, errorMsg(2))
        fi .
    eq < OID : CID | ATS, module: M > parse('gen`ind-invariant_.['bubble[ARG]]) = < OID : CID | ATS, module: M > parse('generate`ind-invariant_.['bubble[ARG]]) .

    ceq [do-gen-inv] : < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | Q), tmpCmd: TMP, pos: POS > genInvariant(M, ARG) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: genInvariant(M, ARG, none, LEMMAS, 1), lastCmd: (TMP | 'generate), tmpCmd: TMP, pos: POS >
        if toStringGen(M, genInvariant(M, ARG, none, LEMMAS, 1), LEMMAS, POS) :: String
        then write(stdout, OID, "\n  " + toStringGen(M, genInvariant(M, ARG, none, LEMMAS, 1), LEMMAS, POS) + "\n\n")
        else write(stdout, OID, errorMsg(0))
        fi
    if Q == 'generate or-else Q == 'noType .

    eq [do-gen-inv-reset] : < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | Q), tmpCmd: TMP, pos: POS > genInvariant(M, ARG) = 
        < OID : CID | ATS, module: M, lemmasui: mt, lastRes: genInvariant(M, ARG, none, mt, 1), lastCmd: (TMP | 'generate), tmpCmd: TMP, pos: "" >
        if toStringGen(M, genInvariant(M, ARG, none, mt, 1), mt, "") :: String
        then write(stdout, OID, "\n  " + toStringGen(M, genInvariant(M, ARG, none, mt, 1), mt, "") + "\n\n")
        else write(stdout, OID, errorMsg(0))
        fi [owise] .

    --- check INVARIANT1 subsumed by INVARIANT2 .
    eq < OID : CID | ATS, module: M > parse('check_subsumed`by_.['bubble[ARG1],'bubble[ARG2]]) = 
        if (parseInvariant(M, downTerm(ARG1, 'nil.QidList)) :: TermList) and-then (parseInvariant(M, downTerm(ARG2, 'nil.QidList)) :: TermList)
        then < OID : CID | ATS, module: M > checkSubsumed(M, parseInvariant(M, downTerm(ARG1, 'nil.QidList)), parseInvariant(M, downTerm(ARG2, 'nil.QidList)))
        else < OID : CID | ATS, module: M > write(stdout, oid, errorMsg(2))
        fi .
    
    ceq [do-check-sub] : < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | Q), tmpCmd: TMP > checkSubsumed(M, ARG1, ARG2) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: checkSubsumed(M, ARG1, ARG2, none, LEMMAS), lastCmd: (TMP | 'subsumption), tmpCmd: TMP >
        if toStringSub(M, checkSubsumed(M, ARG1, ARG2, none, LEMMAS), LEMMAS) :: String
        then write(stdout, OID, "\n  " + toStringSub(M, checkSubsumed(M, ARG1, ARG2, none, LEMMAS), LEMMAS) + "\n\n")
        else write(stdout, OID, errorMsg(0))
        fi
    if Q == 'subsumption or-else Q == 'noType .

    eq [do-check-sub-reset] : < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | Q), tmpCmd: TMP > checkSubsumed(M, ARG1, ARG2) = 
        < OID : CID | ATS, module: M, lemmasui: mt, lastRes: checkSubsumed(M, ARG1, ARG2, none, mt), lastCmd: (TMP | 'subsumption), tmpCmd: TMP >
        if toStringSub(M, checkSubsumed(M, ARG1, ARG2, none, mt), mt) :: String
        then write(stdout, OID, "\n  " + toStringSub(M, checkSubsumed(M, ARG1, ARG2, none, mt), mt) + "\n\n")
        else write(stdout, OID, errorMsg(0))
        fi .

    --- intersect INVARIANT1 with INVARIANT2 .
    eq < OID : CID | ATS, module: M > parse('intersect_with_.['bubble[ARG1],'bubble[ARG2]]) = 
        if (parseInvariant(M, downTerm(ARG1, 'nil.QidList)) :: TermList) and-then (parseInvariant(M, downTerm(ARG2, 'nil.QidList)) :: TermList)
        then < OID : CID | ATS, module: M > checkIntersect(M, parseInvariant(M, downTerm(ARG1, 'nil.QidList)), parseInvariant(M, downTerm(ARG2, 'nil.QidList)))
        else < OID : CID | ATS, module: M > write(stdout, oid, errorMsg(2))
        fi .

    eq [do-check-int] : < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: OUTPUT, lastCmd: (CMD | Q), tmpCmd: TMP > checkIntersect(M, ARG1, ARG2) = 
        < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastRes: checkIntersection(M, ARG1, ARG2, none, LEMMAS), lastCmd: (TMP | 'intersect), tmpCmd: TMP >
        if toStringInt(M, checkIntersection(M, ARG1, ARG2, none, LEMMAS), LEMMAS) :: String
        then write(stdout, OID, "\n  " + toStringInt(M, checkIntersection(M, ARG1, ARG2, none, LEMMAS), LEMMAS) + "\n\n")
        else write(stdout, OID, errorMsg(0))
        fi .

    --- Parse Invariant
    op parseInvariant : Module QidList -> [TermList] .
    ceq parseInvariant(M, QL) = parseInvariant'(M, NTL)
        if '_\/_[NTL] := getTerm(metaNormalize(upModule('DM-CHECK-DISJUNCTION, false), getTerm(metaParse(upModule('DM-CHECK-DISJUNCTION, false), none, QL, anyType)))) .
    eq parseInvariant(M, QL) = parseInvariant'(M, getTerm(metaNormalize(upModule('DM-CHECK-DISJUNCTION, false), getTerm(metaParse(upModule('DM-CHECK-DISJUNCTION, false), none, QL, anyType))))) [ owise ] .

    op parsePattern : Module QidList -> [TermList] .
    eq parsePattern(M, QL) = parseInvariant'(M, getTerm(metaNormalize(upModule('DM-CHECK-DISJUNCTION, false), getTerm(metaParse(upModule('DM-CHECK-DISJUNCTION, false), none, QL, anyType))))) .

    op parseInvariant' : Module TermList -> [TermList] .
    eq parseInvariant'(M, empty) = empty .
    eq parseInvariant'(M, ('_|_['bubble[T1],'true.Bool], TL)) = '_|_[getTerm(metaParse(M, downTerm(T1, (nil).QidList), anyType)),'true.NuITP-Bool], parseInvariant'(M, TL) .
    eq parseInvariant'(M, ('_|_['bubble[T],'_=_['bubble[T1],'bubble[T2]]], TL)) = '_|_[getTerm(metaParse(M, downTerm(T, (nil).QidList), anyType)),'_=_[getTerm(metaParse(M, downTerm(T1, (nil).QidList), anyType)),getTerm(metaParse(M, downTerm(T2, (nil).QidList), anyType))]], parseInvariant'(M, TL) .
    eq parseInvariant'(M, ('_|_['bubble[T],'_/\_[NTL]], TL)) = '_|_[getTerm(metaParse(M, downTerm(T, (nil).QidList), anyType)), '_/\_[parseInvariant''(M, NTL)]], parseInvariant'(M, TL) .
    eq parseInvariant'(M, ('_|_['bubble[T],'_\/_[NTL]], TL)) = '_|_[getTerm(metaParse(M, downTerm(T, (nil).QidList), anyType)), '_\/_[parseInvariant''(M, NTL)]], parseInvariant'(M, TL) .
    
    op parseInvariant'' : Module TermList -> [TermList] .
    eq parseInvariant''(M, empty) = empty .
    eq parseInvariant''(M, '_=_['bubble[T1],'bubble[T2]]) = ('_=_[getTerm(metaParse(M, downTerm(T1, (nil).QidList), anyType)),getTerm(metaParse(M, downTerm(T2, (nil).QidList), anyType))]) .
    eq parseInvariant''(M, ('_=_['bubble[T1],'bubble[T2]], NTL)) = (('_=_[getTerm(metaParse(M, downTerm(T1, (nil).QidList), anyType)),getTerm(metaParse(M, downTerm(T2, (nil).QidList), anyType))]),parseInvariant''(M, NTL)) .

    op parseLemma : Module QidList -> [Term] .
    ceq parseLemma(M, QL) = getTerm(metaNormalize(M, '_->_[GAMMA, DELTA]))
        if '_->_[GAMMA,DELTA] := getTerm(metaParse(M, none, QL, 'NuITP-Clause)) .
    ceq parseLemma(M, QL) = getTerm(metaNormalize(M, '_->_['true.NuITP-Bool, getTerm(metaParse(M, none, QL, 'NuITP-Clause))]))
        if getTerm(metaParse(M, none, QL, anyType)) :: Term .

    --- Add Lemma
    eq < OID : CID | ATS, module: noModule > parse('add`lemma_.['bubble[ARG1]]) = < OID : CID | ATS, module: noModule > write(stdout, oid, errorMsg(1)) .
    eq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: ("" | 'noType) > parse('add`lemma_.['bubble[ARG1]]) = 
        if parseLemma(M, downTerm(ARG1, (nil).QidList)) :: Term
        then < OID : CID | ATS, module: M, lemmasui: LEMMAS ;; parseLemma(M, downTerm(ARG1, (nil).QidList)), lastCmd: ("" | 'noType) > write(stdout, OID, "\n\033[1;32m  Lemma added successfully.\033[0m\n\n")
        else < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: ("" | 'noType) > write(stdout, oid, errorMsg(4))
        fi .

    eq < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | LSTCMD), tmpCmd: TMP > parse('add`lemma_.['bubble[ARG1]]) = 
        if parseLemma(M, downTerm(ARG1, (nil).QidList)) :: Term
        then < OID : CID | ATS, module: M, lemmasui: LEMMAS ;; parseLemma(M, downTerm(ARG1, (nil).QidList)), lastCmd: (CMD | LSTCMD), tmpCmd: CMD > parseCommand(M, OID, CMD)
        else < OID : CID | ATS, module: M, lemmasui: LEMMAS, lastCmd: (CMD | LSTCMD), tmpCmd: TMP > write(stdout, oid, errorMsg(4))
        fi .  
endm

set show command off .

erew in DM-CHECK-UI : init .

